-- ECG Lab Beta: anonymous AI access protection.
-- Stores only a SHA-256 bucket key generated by the Edge Function; no raw IP is stored.

create table if not exists public.ai_request_limits (
  bucket_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now()
);

alter table public.ai_request_limits enable row level security;

revoke all on table public.ai_request_limits from public, anon, authenticated;
grant select, insert, update, delete on table public.ai_request_limits to service_role;

create index if not exists ai_request_limits_updated_at_idx
  on public.ai_request_limits(updated_at);

create or replace function public.consume_ai_quota(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit, 1), 1000));
  v_window integer := greatest(60, least(coalesce(p_window_seconds, 3600), 86400));
  v_count integer;
begin
  if p_key is null or length(p_key) < 16 or length(p_key) > 256 then
    return false;
  end if;

  insert into public.ai_request_limits as q (
    bucket_key, window_started_at, request_count, updated_at
  ) values (
    p_key, now(), 1, now()
  )
  on conflict (bucket_key) do update
  set
    window_started_at = case
      when q.window_started_at <= now() - make_interval(secs => v_window) then now()
      else q.window_started_at
    end,
    request_count = case
      when q.window_started_at <= now() - make_interval(secs => v_window) then 1
      else q.request_count + 1
    end,
    updated_at = now()
  returning request_count into v_count;

  -- Opportunistic cleanup keeps the beta table small without a cron dependency.
  if random() < 0.01 then
    delete from public.ai_request_limits
    where updated_at < now() - interval '7 days';
  end if;

  return v_count <= v_limit;
end;
$$;

revoke all on function public.consume_ai_quota(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_ai_quota(text, integer, integer) to service_role;
