/* ECG Lab — curated English content layer.
   This file intentionally does NOT translate Portuguese word-by-word.
   It builds complete English educational data from stable IDs/categories. */
(function(){
  const PT_STUDY=window.ECG_STUDY_CONTENT;
  const PT_LIBRARY=window.ECG_REAL_LIBRARY;

  const C={
    sinus:{label:'Sinus rhythm',group:'rhythm',explanation:'Regular rhythm with a consistent sinus P wave before every QRS, a 1:1 P:QRS relationship, and a narrow QRS complex.'},
    sinus_brady:{label:'Sinus bradycardia',group:'rhythm',explanation:'Sinus P waves precede every QRS, but the heart rate is below the usual adult resting range.'},
    sinus_tachy:{label:'Sinus tachycardia',group:'rhythm',explanation:'A regular fast rhythm with small but visible sinus P waves preceding each QRS and a gradual physiologic pattern rather than abrupt onset.'},
    sinus_arrhythmia:{label:'Sinus arrhythmia',group:'rhythm',explanation:'Cyclic R–R variation is present while sinus P waves continue to precede every QRS.'},
    afib:{label:'Atrial fibrillation',group:'rhythm',explanation:'The R–R intervals are irregularly irregular, organized P waves are absent, and the baseline shows fibrillatory atrial activity.'},
    flutter:{label:'Atrial flutter',group:'rhythm',explanation:'Rapid organized atrial activity produces repetitive flutter waves, with fixed or variable AV conduction.'},
    svt:{label:'Supraventricular tachycardia',group:'rhythm',explanation:'A regular narrow-complex tachycardia is present; atrial activity may be hidden within the QRS or T wave.'},
    psvt:{label:'Paroxysmal supraventricular tachycardia',group:'rhythm',explanation:'A regular narrow-complex tachycardia with abrupt onset and termination, supporting a paroxysmal SVT mechanism.'},
    paced:{label:'Ventricular paced rhythm',group:'rhythm',explanation:'Pacing spikes precede captured ventricular depolarizations, usually followed by a wide paced QRS complex.'},
    bigeminy:{label:'Ventricular bigeminy',group:'ectopy',explanation:'A ventricular premature complex follows each sinus beat, creating a repeating normal–PVC pattern.'},
    trigeminy:{label:'Ventricular trigeminy',group:'ectopy',explanation:'A ventricular premature complex occurs every third beat, typically after two sinus beats.'},
    pvc:{label:'Premature ventricular complex (PVC)',group:'ectopy',explanation:'An early wide ventricular complex occurs without a normal preceding sinus P wave and may be followed by a compensatory pause.'},
    pac:{label:'Premature atrial complex (PAC)',group:'ectopy',explanation:'An early atrial depolarization produces a premature P wave with a usually narrow QRS complex.'},
    avb1:{label:'First-degree AV block',group:'conduction',explanation:'Every P wave conducts to the ventricles, but the PR interval is prolonged and remains constant.'},
    mobitz1:{label:'Second-degree AV block — Mobitz I (Wenckebach)',group:'conduction',explanation:'The PR interval progressively lengthens until a P wave is not conducted, after which the cycle resets.'},
    mobitz2:{label:'Second-degree AV block — Mobitz II',group:'conduction',explanation:'Conducted beats have a fixed PR interval, while some P waves are suddenly not followed by a QRS complex.'},
    avb3:{label:'Third-degree AV block (complete heart block)',group:'conduction',explanation:'Atrial and ventricular rhythms are independent, demonstrating AV dissociation with an escape rhythm.'},
    vt:{label:'Ventricular tachycardia',group:'ventricular',explanation:'A rapid regular wide-complex rhythm with a ventricular morphology is present; in the appropriate context this should be treated as ventricular tachycardia until proven otherwise.'},
    vf:{label:'Ventricular fibrillation',group:'ventricular',explanation:'Chaotic ventricular electrical activity is present without organized QRS complexes or an effective ventricular rhythm.'}
  };

  const LESSON={
    fundamentals:{title:'ECG Fundamentals',summary:'Learn ECG paper, calibration, waves, intervals, and a repeatable interpretation method.',objectives:['Confirm paper speed and calibration before interpreting the tracing','Relate P waves, PR, QRS, ST-T, and QT to cardiac electrical activity','Use the same systematic sequence for every ECG'],sections:[['Before interpreting the rhythm',['Confirm standard settings when applicable: 25 mm/s and 10 mm/mV.','Check signal quality, artifact, lead placement, and the clinical context.','Describe objective findings before naming a diagnosis.']],['A systematic sequence',['Rate → regularity → P waves → PR interval → QRS width → axis when relevant → ST-T → QT/QTc → conclusion.','For tachycardias, first separate regular from irregular and narrow from wide QRS.']],['Core measurements',['At 25 mm/s, one small box equals 0.04 s and one large box equals 0.20 s.','A QRS duration of 120 ms or more is considered wide in adults.']]],pitfalls:['Interpreting without checking calibration','Calling artifact an arrhythmia','Naming a diagnosis before evaluating P waves and QRS morphology']},
    normal:{title:'Normal ECG and Sinus Rhythm',summary:'Recognize sinus rhythm and understand what a normal rhythm strip actually requires.',objectives:['Identify a sinus P wave before every QRS','Confirm a 1:1 P:QRS relationship','Avoid labeling every regular rhythm as sinus'],sections:[['Key criteria',['The rhythm is generally regular with an adult resting rate commonly between 60 and 100 bpm.','P-wave morphology is consistent and every P wave is followed by a QRS.','The QRS is usually narrow unless a conduction abnormality is present.']],['Important limitation',['A regular rhythm without clearly identifiable sinus P waves should not automatically be called sinus rhythm.']]],pitfalls:['Mistaking artifact for P waves','Overlooking a regular junctional rhythm']},
    sinus_brady:{title:'Sinus Bradycardia',summary:'Sinus rhythm is preserved, but the rate is slower than expected for the clinical setting.',objectives:['Confirm sinus P waves before each QRS','Differentiate physiologic bradycardia from pathologic causes','Assess symptoms and perfusion rather than the rate alone'],sections:[['ECG pattern',['A sinus P wave precedes every QRS and the PR interval is usually stable.','The adult ventricular rate is below 60 bpm.']],['Clinical context',['Bradycardia may be physiologic in trained athletes or during sleep.','Medication effects, hypothyroidism, hypothermia, ischemia, and sinus-node dysfunction may also contribute.']]],pitfalls:['Confusing complete heart block with sinus bradycardia','Treating the number rather than assessing perfusion and symptoms']},
    sinus_tachy:{title:'Sinus Tachycardia',summary:'An accelerated sinus rhythm, usually reflecting physiologic demand or a compensatory response.',objectives:['Find a sinus P wave before every QRS','Recognize gradual acceleration and deceleration','Search for the clinical driver of the tachycardia'],sections:[['ECG pattern',['The rhythm is regular with a sinus P wave before each QRS.','At faster rates, the P wave may become small or partially merge with the preceding T wave, but it should remain identifiable.']],['Common causes',['Exercise, fever, pain, anxiety, hypovolemia, anemia, infection, hypoxia, and hyperthyroidism are common triggers.']]],pitfalls:['Calling SVT sinus tachycardia when onset is abrupt','Missing small P waves at high rates','Focusing on rate control without considering the underlying cause']},
    sinus_arrhythmia:{title:'Sinus Arrhythmia',summary:'Cyclic R–R variation occurs while the sinus mechanism remains intact.',objectives:['Relate R–R variation to respiration','Confirm sinus P waves before all QRS complexes','Differentiate sinus arrhythmia from atrial fibrillation'],sections:[['Pattern',['P-wave morphology remains sinus and consistent.','R–R intervals vary, often increasing and decreasing with respiration.']]],pitfalls:['Calling every irregular rhythm atrial fibrillation','Ignoring preserved sinus P waves']},
    afib:{title:'Atrial Fibrillation',summary:'Disorganized atrial activity produces an irregularly irregular ventricular response.',objectives:['Confirm the absence of organized P waves','Recognize irregularly irregular R–R intervals','Differentiate AF from variable flutter and frequent atrial ectopy'],sections:[['ECG pattern',['No consistent organized P waves are seen.','The ventricular rhythm is irregularly irregular.','The QRS is usually narrow unless a separate conduction abnormality is present.']]],pitfalls:['Mistaking coarse fibrillatory waves for organized P waves','Calling any irregular rhythm AF without checking atrial activity']},
    flutter:{title:'Atrial Flutter',summary:'Rapid organized atrial activity produces repetitive flutter waves with fixed or variable AV conduction.',objectives:['Recognize flutter-wave morphology','Identify 2:1, 3:1, 4:1, or variable AV conduction','Differentiate flutter with 2:1 conduction from sinus tachycardia and SVT'],sections:[['ECG pattern',['Atrial activity is rapid and organized, often near 300/min.','Flutter waves may create a sawtooth baseline.','Ventricular rate depends on the AV conduction ratio.']]],pitfalls:['Missing flutter when 2:1 conduction creates a regular rate near 150 bpm','Confusing variable flutter with atrial fibrillation']},
    svt:{title:'Supraventricular Tachycardia',summary:'A usually regular narrow-complex tachycardia originating above the ventricles.',objectives:['Recognize a regular narrow-complex tachycardia','Understand that P waves may be hidden in the QRS or T wave','Differentiate SVT from sinus tachycardia and atrial flutter'],sections:[['ECG pattern',['The rhythm is usually very regular.','QRS complexes are narrow in the absence of aberrant conduction.','Atrial activity may be difficult to see.']]],pitfalls:['Assuming every regular narrow tachycardia is sinus','Ignoring abrupt onset and termination']},
    psvt:{title:'Paroxysmal Supraventricular Tachycardia',summary:'Episodes of SVT that begin and end abruptly.',objectives:['Recognize abrupt onset and termination','Identify a regular narrow-complex tachycardia during the episode','Differentiate PSVT from the gradual acceleration of sinus tachycardia'],sections:[['Clinical clue',['The history of sudden onset and sudden termination is often as important as the rhythm strip.']]],pitfalls:['Calling gradual sinus tachycardia PSVT','Overlooking retrograde or hidden atrial activity']},
    paced:{title:'Ventricular Paced Rhythm',summary:'Recognize pacing spikes and confirm the relationship between the stimulus and ventricular capture.',objectives:['Identify a pacing spike','Assess capture conceptually','Avoid confusing a paced wide QRS with ventricular tachycardia or bundle-branch block'],sections:[['ECG pattern',['A pacing spike precedes the captured ventricular complex.','Ventricular pacing typically produces a wide QRS morphology.']]],pitfalls:['Calling every wide paced QRS ventricular tachycardia','Ignoring loss of capture when a spike is not followed by depolarization']},
    bigeminy:{title:'Ventricular Bigeminy',summary:'A repeating pattern in which a PVC follows each sinus beat.',objectives:['Recognize alternating sinus and ventricular beats','Confirm the premature wide morphology of the PVC','Assess the underlying rhythm separately from the ectopy'],sections:[['Pattern',['Normal beat → PVC → normal beat → PVC.']]],pitfalls:['Describing the pattern without identifying the ventricular ectopy','Confusing bigeminy with trigeminy']},
    trigeminy:{title:'Ventricular Trigeminy',summary:'A PVC recurs every third beat in a repeating pattern.',objectives:['Recognize two sinus beats followed by one PVC','Differentiate trigeminy from bigeminy','Review electrolytes and structural heart disease when clinically relevant'],sections:[['Pattern',['Sinus beat → sinus beat → PVC, then the sequence repeats.']]],pitfalls:['Counting the ectopy pattern incorrectly','Ignoring the morphology of the premature beat']},
    pvc:{title:'Premature Ventricular Complex (PVC)',summary:'A premature ventricular beat, usually wide and morphologically different from the baseline rhythm.',objectives:['Identify an early wide QRS','Recognize a compensatory pause when present','Differentiate a PVC from a PAC with aberrant conduction'],sections:[['ECG pattern',['The premature QRS is wide and bizarre compared with baseline.','A normal sinus P wave does not usually precede the PVC.','A compensatory pause may follow.']]],pitfalls:['Calling every wide premature beat a PVC without checking for an early P wave','Ignoring frequent or complex ectopy in the clinical context']},
    pac:{title:'Premature Atrial Complex (PAC)',summary:'An early atrial beat, usually with an abnormal premature P wave and a narrow QRS.',objectives:['Identify an early P wave with altered morphology','Differentiate a PAC from a PVC','Recognize a blocked PAC as a possible cause of a pause'],sections:[['ECG pattern',['The premature P wave may deform the preceding T wave.','The QRS is usually narrow unless aberrant conduction occurs.']]],pitfalls:['Missing a P wave hidden in the T wave','Calling an aberrantly conducted PAC a PVC']},
    avb1:{title:'First-Degree AV Block',summary:'1:1 AV conduction is preserved, but the PR interval is prolonged and constant.',objectives:['Confirm that every P wave conducts','Measure a prolonged PR interval','Avoid calling a long PR interval a dropped beat'],sections:[['ECG pattern',['Each P wave is followed by a QRS complex.','The PR interval is longer than 200 ms and remains constant.']]],pitfalls:['Calling first-degree block second-degree block','Ignoring medication effects or AV-nodal disease in context']},
    mobitz1:{title:'Second-Degree AV Block — Mobitz I (Wenckebach)',summary:'Progressive PR prolongation occurs until a P wave is not conducted.',objectives:['Compare consecutive PR intervals','Identify the dropped QRS after progressive PR lengthening','Differentiate Wenckebach from Mobitz II'],sections:[['ECG pattern',['PR intervals progressively lengthen.','Eventually a P wave is not followed by a QRS, and the cycle restarts.']]],pitfalls:['Diagnosing Wenckebach from a pause alone','Failing to compare sequential PR intervals']},
    mobitz2:{title:'Second-Degree AV Block — Mobitz II',summary:'Conducted beats have a fixed PR interval, with intermittent sudden failure of ventricular conduction.',objectives:['Identify a non-conducted P wave','Confirm a stable PR interval in conducted beats','Recognize the risk of progression to advanced block'],sections:[['ECG pattern',['The PR interval of conducted beats remains constant.','Some P waves are suddenly not followed by QRS complexes.']]],pitfalls:['Confusing Mobitz II with Wenckebach','Assuming a stable patient makes the rhythm low risk']},
    avb3:{title:'Third-Degree AV Block',summary:'Atrial and ventricular depolarizations occur independently because no atrial impulses conduct to the ventricles.',objectives:['Demonstrate AV dissociation','Separate atrial and ventricular rates','Recognize the ventricular escape rhythm'],sections:[['ECG pattern',['P waves march through at their own rate.','QRS complexes occur at a separate escape rate.','There is no fixed PR relationship.']]],pitfalls:['Trying to force a consistent PR interval','Mistaking independent P waves for premature atrial beats']},
    vt:{title:'Ventricular Tachycardia',summary:'A rapid wide-complex rhythm originating in the ventricles.',objectives:['Recognize a regular monomorphic wide-complex tachycardia','Use structural heart disease or prior MI as an important clue','Avoid assuming that hemodynamic stability means SVT'],sections:[['ECG pattern',['The rhythm is fast, usually regular, and the QRS complexes are wide.','Monomorphic VT has a similar QRS shape from beat to beat.']]],pitfalls:['Calling a wide-complex tachycardia SVT simply because the patient is stable','Ignoring the clinical history of scar or structural disease']},
    vf:{title:'Ventricular Fibrillation',summary:'Chaotic ventricular electrical activity without organized QRS complexes or effective cardiac output.',objectives:['Recognize the absence of organized QRS complexes','Differentiate fine VF from artifact or asystole','Always correlate the tracing with the patient'],sections:[['ECG pattern',['Electrical activity is chaotic and continuously variable.','There is no organized ventricular rhythm.']]],pitfalls:['Calling motion artifact VF without checking the patient','Mistaking fine VF for asystole without adequate signal assessment']},
    ischemia:{title:'Ischemia and ST-T Changes',summary:'Learn a safe framework for evaluating ST-T abnormalities and understanding the limits of a single-lead rhythm strip.',objectives:['Define the baseline and compare contiguous leads on a 12-lead ECG','Look for reciprocal changes and clinical correlation','Recognize common mimics of ST elevation'],sections:[['Important limitation',['Lead II alone is not sufficient to localize ischemia or diagnose a STEMI pattern.','Use a 12-lead ECG, symptoms, serial tracings, and biomarkers for ischemia assessment.']],['Common mimics',['Early repolarization, pericarditis, ventricular aneurysm, bundle-branch block, and hypertrophy may alter ST-T morphology.']]],pitfalls:['Diagnosing STEMI from ST elevation in a single rhythm lead','Ignoring serial ECG changes and the clinical context']}
  };

  const MODULES=[
    ['m1',1,'Fundamentals','ECG paper, waves, intervals, calibration, and a systematic method.',['fundamentals','normal']],
    ['m2',1,'Sinus Rhythms','Sinus rhythm, sinus bradycardia, sinus tachycardia, and sinus arrhythmia.',['sinus_brady','sinus_tachy','sinus_arrhythmia']],
    ['m3',2,'Atrial Arrhythmias and SVT','Atrial fibrillation, atrial flutter, SVT, and paroxysmal SVT.',['afib','flutter','svt','psvt']],
    ['m4',2,'Ectopy','PACs, PVCs, ventricular bigeminy, and trigeminy.',['pac','pvc','bigeminy','trigeminy']],
    ['m5',3,'AV Blocks','First-degree AV block, Mobitz I, Mobitz II, and complete heart block.',['avb1','mobitz1','mobitz2','avb3']],
    ['m6',3,'Ventricular Rhythms','Ventricular tachycardia and ventricular fibrillation.',['vt','vf']],
    ['m7',3,'Pacemaker Rhythms','Pacing spikes, capture, and interpretation of ventricular paced rhythms.',['paced']],
    ['m8',4,'Ischemia and ST-T','ST-T interpretation, clinical correlation, and the limitations of single-lead rhythm strips.',['ischemia']],
    ['m9',4,'Complete Clinical Cases','190 fictional clinical cases across the rhythm library, with mild diagnostic traps.',['normal','sinus_brady','sinus_tachy','sinus_arrhythmia','afib','flutter','svt','psvt','paced','bigeminy','trigeminy','pvc','pac','avb1','mobitz1','mobitz2','avb3','vt','vf']]
  ].map(([key,level,title,description,lesson_keys])=>({key,level,title,description,lesson_keys,unlocked:true}));

  const CASE_TITLES=['Routine assessment','Urgent-care evaluation','Outpatient follow-up','Emergency department presentation','Postoperative monitoring','Medication review','Telemetry finding','Exercise-related symptoms','Older adult with dizziness','Young adult with palpitations'];
  const VITALS=['BP 118/72, HR 72, RR 16, SpO₂ 99%, T 36.6°C','BP 126/78, HR 84, RR 18, SpO₂ 98%, T 36.7°C','BP 112/68, HR 58, RR 16, SpO₂ 99%, T 36.5°C','BP 104/64, HR 108, RR 20, SpO₂ 97%, T 37.1°C','BP 138/82, HR 76, RR 17, SpO₂ 98%, T 36.8°C'];
  const COMMON_LABS=[['Hemoglobin within reference range','Potassium 4.1 mmol/L','Magnesium 2.0 mg/dL'],['High-sensitivity troponin negative when clinically indicated','Potassium 3.9 mmol/L','Creatinine 0.9 mg/dL'],['CBC without major abnormalities','Electrolytes within reference range','TSH within reference range']];

  const PROFILE={
    sinus:{chief:'No current cardiac symptoms.',history:'No known structural heart disease; functional status is preserved.',meds:'No relevant rhythm-active medications.',exam:['Regular pulse, normal perfusion, no signs of heart failure.'],imaging:'No acute structural abnormality is identified when imaging is clinically indicated.',trap:'A normal clinical context is not a reason to invent an ECG abnormality.',learning:'Confirm sinus P waves and a 1:1 P:QRS relationship before calling the rhythm sinus.'},
    sinus_brady:{chief:'Slow pulse with either no symptoms or mild fatigue/lightheadedness.',history:'Context may include athletic conditioning, sleep, vagal tone, medication effect, or sinus-node disease.',meds:'Review beta-blockers, non-dihydropyridine calcium-channel blockers, digoxin, and other rate-slowing agents.',exam:['Bradycardic pulse; perfusion may be normal or reduced depending on the case.'],imaging:'Echocardiography is guided by the suspected underlying disease rather than the rhythm alone.',trap:'Do not assume every slow regular rhythm is sinus; verify P waves before every QRS.',learning:'Rate alone does not determine severity—symptoms and perfusion matter.'},
    sinus_tachy:{chief:'Palpitations or a fast pulse in a context of physiologic stress or compensation.',history:'Look for fever, pain, anxiety, exercise, dehydration, anemia, infection, hypoxia, or hyperthyroidism.',meds:'Review stimulants, decongestants, caffeine, and medications that may contribute to tachycardia.',exam:['Rapid regular pulse; findings depend on the underlying trigger.'],imaging:'Imaging is directed by the suspected cause, not by sinus tachycardia itself.',trap:'At high rates the sinus P wave can be small and partly overlap the T wave; it should not simply disappear.',learning:'Sinus tachycardia usually accelerates and decelerates gradually and has a physiologic driver.'},
    sinus_arrhythmia:{chief:'An irregular pulse, often discovered incidentally in a young or otherwise healthy person.',history:'Symptoms are usually absent; the rhythm may vary with respiration.',meds:'No rhythm-specific medication is required for a physiologic pattern.',exam:['Irregular pulse with otherwise normal perfusion and examination.'],imaging:'No additional imaging is usually required for isolated physiologic sinus arrhythmia.',trap:'Irregular does not automatically mean atrial fibrillation.',learning:'Preserved sinus P waves before every QRS distinguish sinus arrhythmia from AF.'},
    afib:{chief:'Palpitations, fatigue, dyspnea, dizziness, or an incidentally detected irregular pulse.',history:'Assess duration, prior episodes, structural heart disease, thyroid disease, alcohol exposure, and stroke-risk factors.',meds:'Review anticoagulants, rate-control agents, antiarrhythmics, and interacting medications.',exam:['Irregularly irregular pulse; hemodynamic findings vary by ventricular rate and comorbidity.'],imaging:'Echocardiography may assess chamber size, ventricular function, and structural disease.',trap:'Do not diagnose AF from irregularity alone—organized P waves must be absent.',learning:'Irregularly irregular R–R intervals plus absent organized P waves strongly support AF.'},
    flutter:{chief:'Palpitations or persistent tachycardia, sometimes with a ventricular rate near 150 bpm.',history:'Consider atrial disease, postoperative states, heart failure, pulmonary disease, or prior atrial arrhythmias.',meds:'Review AV-nodal blockers, antiarrhythmics, and anticoagulation history.',exam:['Pulse may be regular with fixed conduction or irregular with variable conduction.'],imaging:'Echocardiography is often used to assess structural disease and ventricular function.',trap:'A regular rate near 150 bpm can represent atrial flutter with 2:1 conduction.',learning:'Search carefully for repetitive flutter waves and determine the AV conduction ratio.'},
    svt:{chief:'Sudden rapid palpitations with a regular pulse.',history:'Episodes may start abruptly and may occur without known structural heart disease.',meds:'Review stimulants and prior rhythm medications.',exam:['Rapid regular pulse; perfusion may remain preserved in stable episodes.'],imaging:'Structural imaging is often normal in otherwise healthy patients.',trap:'A regular narrow tachycardia is not automatically sinus tachycardia.',learning:'Regular narrow QRS tachycardia with poorly visible P waves supports SVT after considering flutter and sinus tachycardia.'},
    psvt:{chief:'Abrupt episodes of rapid palpitations that also stop suddenly.',history:'The onset/termination pattern is a major diagnostic clue and often distinguishes PSVT from sinus tachycardia.',meds:'Review stimulants and prior use of AV-nodal or antiarrhythmic medications.',exam:['During the episode the pulse is fast and very regular; examination may otherwise be normal.'],imaging:'Echocardiography may be normal when no structural heart disease is present.',trap:'Do not ignore the history of abrupt onset and termination.',learning:'PSVT is a clinical-rhythm pattern, not merely a high heart rate.'},
    paced:{chief:'Routine device follow-up, bradycardia history, or telemetry showing a paced rhythm.',history:'A pacemaker may have been implanted for symptomatic bradycardia or advanced AV block.',meds:'Chronic cardiovascular medications vary by the underlying disease.',exam:['Perfusion is usually adequate when pacing is effective; inspect the device site when clinically relevant.'],imaging:'Chest imaging can confirm generator and lead position; echocardiography reflects the underlying cardiac condition.',trap:'A wide paced QRS may resemble VT or bundle-branch block—look for pacing spikes and capture.',learning:'A pacing spike followed by a ventricular complex demonstrates capture.'},
    bigeminy:{chief:'Palpitations or a sensation of skipped beats.',history:'Ectopy may be associated with stimulants, stress, electrolyte abnormalities, or structural heart disease.',meds:'Review stimulants, diuretics, and proarrhythmic medications.',exam:['A pulse deficit may occur during PVCs; perfusion is often preserved in isolated ectopy.'],imaging:'Echocardiography may be used when structural heart disease or frequent ectopy is a concern.',trap:'Describe both the ectopic beat and the repeating pattern.',learning:'Bigeminy means every sinus beat is followed by a PVC.'},
    trigeminy:{chief:'Intermittent palpitations or skipped beats.',history:'Clinical significance depends on ectopy burden, symptoms, electrolytes, and underlying heart disease.',meds:'Review stimulants, diuretics, and medications that may affect ventricular excitability.',exam:['Pulse may feel irregular because some premature beats generate a weaker peripheral pulse.'],imaging:'Structural evaluation is guided by symptoms, ectopy burden, and cardiac history.',trap:'Count the pattern carefully: two sinus beats, then one PVC.',learning:'Trigeminy describes timing; the premature beat still needs to be identified as ventricular.'},
    pvc:{chief:'A premature thump, skipped beat, or incidental ventricular ectopy.',history:'Assess stimulant use, electrolyte imbalance, ischemic symptoms, structural disease, and ectopy burden.',meds:'Review stimulants, diuretics, antiarrhythmics, and other proarrhythmic drugs.',exam:['Pulse may briefly become irregular or show a pulse deficit around the premature beat.'],imaging:'Echocardiography may be appropriate when ectopy is frequent or structural disease is suspected.',trap:'An aberrantly conducted PAC can be wide; look for an early atrial P wave.',learning:'A PVC is premature, wide, ventricular in morphology, and usually lacks a normal preceding sinus P wave.'},
    pac:{chief:'Brief palpitations or an incidental premature beat.',history:'PACs may occur with stress, caffeine, alcohol, sleep loss, or normal physiologic states.',meds:'Review stimulants and other agents that may increase atrial ectopy.',exam:['Most isolated PACs occur with normal perfusion and no signs of heart failure.'],imaging:'Additional imaging is usually guided by the broader clinical context.',trap:'The premature P wave may be hidden in the preceding T wave.',learning:'A PAC originates in the atrium and usually conducts with a narrow QRS unless aberrancy occurs.'},
    avb1:{chief:'Often asymptomatic; may be discovered on routine ECG or telemetry.',history:'Consider AV-nodal medications, increased vagal tone, or conduction-system disease.',meds:'Review beta-blockers, non-dihydropyridine calcium-channel blockers, digoxin, and other nodal agents.',exam:['Pulse is usually regular with preserved perfusion.'],imaging:'Imaging is directed by suspected structural disease rather than the PR prolongation alone.',trap:'A long PR interval does not mean a beat was dropped.',learning:'Every P wave conducts 1:1; the PR interval is simply prolonged and constant.'},
    mobitz1:{chief:'May be asymptomatic or cause dizziness, especially when the ventricular rate becomes slow.',history:'Often associated with AV-nodal disease, vagal tone, medications, or inferior ischemia in the right context.',meds:'Review AV-nodal blocking agents.',exam:['Grouped beating may be present; perfusion depends on the ventricular rate.'],imaging:'Echocardiography is guided by the underlying disease; inferior wall abnormalities may be relevant in ischemic settings.',trap:'A single pause is not enough—show progressive PR prolongation before the dropped QRS.',learning:'Wenckebach is defined by progressive PR lengthening followed by a non-conducted P wave.'},
    mobitz2:{chief:'Dizziness, presyncope, syncope, or an incidental telemetry finding.',history:'Often reflects infranodal conduction disease and may occur with structural disease or after cardiac procedures.',meds:'Medication review is important, but it does not exclude intrinsic conduction-system disease.',exam:['Bradycardia and signs of hypoperfusion may be present.'],imaging:'Echocardiography may show structural disease; post-TAVR or post-MI settings increase concern.',trap:'Do not confuse a fixed PR interval with Wenckebach.',learning:'Mobitz II has constant PR intervals in conducted beats with sudden dropped QRS complexes.'},
    avb3:{chief:'Fatigue, dizziness, presyncope, syncope, or hemodynamic instability.',history:'Causes include degenerative conduction disease, ischemia, inflammation, medications, or recent cardiac procedures.',meds:'Review AV-nodal agents and the procedural history.',exam:['Marked bradycardia may reduce perfusion; cannon A waves can occur because atria and ventricles contract independently.'],imaging:'Echocardiography assesses structure and function; recent procedures or MI may suggest the cause.',trap:'Do not search for a fixed PR interval—P waves and QRS complexes are independent.',learning:'Complete heart block is AV dissociation with an independent escape rhythm.'},
    vt:{chief:'Rapid palpitations, dizziness, chest discomfort, syncope, or hemodynamic instability.',history:'Structural heart disease or myocardial scar is common, although VT can occur in other settings.',meds:'Review antiarrhythmics, diuretics, and medications that may prolong repolarization or promote arrhythmia.',exam:['Rapid pulse; stability ranges from preserved blood pressure to shock.'],imaging:'Echocardiography may show reduced EF or scar-related structural disease.',trap:'Hemodynamic stability does not convert a wide-complex VT into SVT.',learning:'A regular monomorphic wide-complex tachycardia in structural heart disease strongly favors VT.'},
    vf:{chief:'Sudden collapse without a pulse.',history:'Potential causes include acute ischemia, cardiomyopathy, electrolyte disturbance, hypoxia, and other reversible causes.',meds:'Medication history may be unavailable at the moment of arrest.',exam:['Unresponsive, pulseless, and apneic or with agonal respirations.'],imaging:'Imaging is obtained only after stabilization or return of spontaneous circulation.',trap:'Always check the patient and exclude artifact before labeling a tracing ventricular fibrillation.',learning:'VF has no organized QRS complexes and no effective cardiac output.'}
  };

  function buildCase(ptCase,key,i){
    const p=PROFILE[key]||PROFILE.sinus;
    const c=C[key]||C.sinus;
    return {id:ptCase.id,title:`${CASE_TITLES[i%CASE_TITLES.length]} — ${c.label}`,difficulty:ptCase.difficulty||Math.min(5,1+Math.floor(i/2)),chief_complaint:p.chief,anamnesis:p.history,medications:p.meds,vitals:VITALS[i%VITALS.length],physical_exam:p.exam,labs:COMMON_LABS[i%COMMON_LABS.length],imaging:p.imaging,ecg_image:ptCase.ecg_image,question:'What is the predominant rhythm, and which ECG and clinical findings support your interpretation?',answer:c.label,reasoning:c.explanation,trap:p.trap,learning_point:p.learning};
  }

  function buildStudy(){
    if(!PT_STUDY) return null;
    const lessons={};
    for(const [key,pt] of Object.entries(PT_STUDY.lessons||{})){
      const m=LESSON[key]; if(!m) continue;
      lessons[key]={...pt,key,title:m.title,summary:m.summary,objectives:m.objectives,sections:m.sections,pitfalls:m.pitfalls,unlocked:true,videos:(pt.videos||[]).map(v=>({...v,note:'Selected external teaching resource. Opens on the original creator’s YouTube channel.'})),references:(pt.references||[]).map(r=>({...r})),cases:(pt.cases||[]).map((c,i)=>buildCase(c,key,i))};
    }
    return {version:'study-en-v2',copyright_note:'Original ECG Lab educational summaries. External videos are linked only to their original channels and are not copied or redistributed. References are provided for verification and further study.',modules:MODULES,lessons};
  }

  function translateOptionLabel(label){
    const direct={'Ritmo sinusal':'Sinus rhythm','Bradicardia sinusal':'Sinus bradycardia','Taquicardia sinusal':'Sinus tachycardia','Arritmia sinusal':'Sinus arrhythmia','Fibrilação atrial':'Atrial fibrillation','Flutter atrial':'Atrial flutter','Taquicardia supraventricular':'Supraventricular tachycardia','TSV paroxística':'Paroxysmal supraventricular tachycardia','Ritmo estimulado por marcapasso':'Ventricular paced rhythm','Bigeminismo ventricular':'Ventricular bigeminy','Trigeminismo ventricular':'Ventricular trigeminy','Extrassístole ventricular (PVC)':'Premature ventricular complex (PVC)','Extrassístole atrial (PAC)':'Premature atrial complex (PAC)','BAV de 1º grau':'First-degree AV block','BAV de 2º grau — Mobitz I':'Second-degree AV block — Mobitz I','BAV de 2º grau — Mobitz II':'Second-degree AV block — Mobitz II','BAV de 3º grau':'Third-degree AV block','BAV de 3º grau (bloqueio AV completo)':'Third-degree AV block (complete heart block)','BAV Mobitz I':'Mobitz I AV block','BAV Mobitz II':'Mobitz II AV block','Taquicardia ventricular':'Ventricular tachycardia','Taquicardia ventricular monomórfica':'Monomorphic ventricular tachycardia','Fibrilação ventricular':'Ventricular fibrillation','Assistolia':'Asystole','Ritmo sinusal em frequência normal':'Normal-rate sinus rhythm','Fibrilação atrial sem estimulação':'Atrial fibrillation without pacing','Bloqueio de ramo esquerdo sem estimulação':'Left bundle branch block without pacing','Extrassístoles isoladas sem padrão':'Isolated premature beats without a repeating pattern'};
    return direct[label]||label;
  }

  const QUESTION_PROMPTS={sinus:'Which rhythm is present on this ECG?',sinus_brady:'Which rhythm best matches this slow regular tracing?',sinus_tachy:'Which rhythm best explains this fast regular tracing with sinus atrial activity?',sinus_arrhythmia:'Which rhythm pattern is present?',afib:'Which rhythm is most compatible with this irregular tracing?',flutter:'Which atrial rhythm is present?',svt:'Which narrow-complex tachycardia pattern is present?',psvt:'Which rhythm best matches this abrupt regular narrow-complex tachycardia?',paced:'Which pacing pattern is present?',bigeminy:'Which ectopic pattern is present?',trigeminy:'Which ectopic pattern is present?',pvc:'What type of premature beat is shown?',pac:'What type of premature beat is shown?',avb1:'Which AV conduction abnormality is present?',mobitz1:'Which degree and type of AV block is present?',mobitz2:'Which degree and type of AV block is present?',avb3:'Which AV block is present?',vt:'Which rhythm is most compatible with this wide-complex tachycardia?',vf:'Which rhythm is present?'};

  function buildEnglishLibrary(){
    if(!PT_LIBRARY) return null;
    const categories=(PT_LIBRARY.categories||[]).map(cat=>({...cat,label:C[cat.key]?.label||cat.label,group:C[cat.key]?.group||cat.group}));
    return {version:'vector-edu-en-v3',categories,load:async()=>{const src=await PT_LIBRARY.load();const cases=(src.cases||[]).map((item,i)=>{const c=C[item.category]||{};return {...item,title:`${c.label||'ECG rhythm'} • variation ${(i%6)+1}`,diagnosis:c.label||item.diagnosis,interpretation:c.label||item.interpretation,explanation:c.explanation||item.explanation,source_name:'ECG Lab — reconstructed educational vector tracing',license:'Educational use within the ECG Lab project',category_label:c.label||item.category_label};});const questions=(src.questions||[]).map(q=>{const c=C[q.category]||{};return {...q,prompt:QUESTION_PROMPTS[q.category]||'Which rhythm is shown on this ECG?',explanation:c.explanation||q.explanation,category_label:c.label||q.category_label,options:(q.options||[]).map(o=>({...o,label:translateOptionLabel(o.label)}))};});return {version:'vector-edu-en-v3',cases,questions,categories,counts:src.counts||Object.fromEntries(categories.map(c=>[c.key,6]))};}};
  }

  window.ECG_STUDY_CONTENT_EN=buildStudy();
  window.ECG_REAL_LIBRARY_EN=buildEnglishLibrary();
})();
