/* ECG Lab — floating, contextual, bilingual AI Tutor.
   Keeps the current activity mounted while the tutor opens, persists conversation locally,
   withholds answers before submission, supports Socratic mode and browser speech recognition,
   and records assistance signals separately from mastery calculations. */
(function(){
  'use strict';
  const VERSION=1;
  const CONV_PREFIX=`ecgLabTutorConversations:v${VERSION}:`;
  const SIGNAL_PREFIX=`ecgLabTutorSignals:v${VERSION}:`;
  const MODE_PREFIX='ecgLabPracticeTutorMode:v1:';
  const ui={open:false,max:false,history:false,useContext:true,socratic:false,thinking:false,activeId:null,width:460,sheet:'mid',recognition:null};
  const isEn=()=>window.ECG_LANG==='en';
  const T=()=>isEn()?{
    name:'AI Tutor',brand:'CardioTutor AI',ask:'Ask a question...',send:'Send',newChat:'+ New conversation',recent:'Recent conversations',context:'Context',useContext:'Use context from this screen',socratic:'Socratic mode',minimize:'Minimize',maximize:'Maximize',restore:'Restore',close:'Close',
    greeting:'Hi! I am your contextual ECG tutor. I can guide your reasoning without taking you away from the activity you are doing.',noContext:'General ECG study',thinking:'Thinking…',voice:'Voice input',voiceUnsupported:'Voice recognition is not supported by this browser.',
    lockedTitle:'Tutor available after you finish this practice exam',lockedBody:'This practice exam is in Exam Mode. To protect the validity of your result, the tutor is locked until the exam is completed.',studyMode:'Study Mode',examMode:'Exam Mode',modeHelp:'Study Mode allows the tutor. Exam Mode locks it until completion.',
    preAnswer:'I can help you reach the answer without revealing it first. Start with rate and regularity, then inspect P waves, the P:QRS relationship, PR interval, and QRS width. What do you notice?',
    demo:'AI responses require Supabase and the ecg-tutor Edge Function. I can still guide you with the current educational context.',genericGuide:'Use a systematic sequence: rate → regularity → P waves → PR → QRS → ST-T → conclusion. Tell me what you see at each step and I will help refine your reasoning.',
    error:'I could not access the tutor: ',newTitle:'New conversation',privacy:'Voice is transcribed in the browser; raw audio is not stored by ECG Lab.',
    qTrain:['Help me interpret this ECG','What finding should I look for?','Explain this rhythm','Give me a hint'],
    qQuestion:['Give me a hint','Explain the concept','How should I reason through this?','Why was my answer wrong?'],
    qCase:['Help with clinical reasoning','Which data matter most?','What should I assess first?','Analyze my reasoning'],
    qStudy:['Explain this simply','Go deeper on this topic','Give me an analogy','Create a question about this'],
    qGeneric:['Explain a concept','Quiz me on ECG interpretation','Review a rhythm with me']
  }:{
    name:'Tutor IA',brand:'CardioTutor IA',ask:'Digite sua pergunta...',send:'Enviar',newChat:'+ Nova conversa',recent:'Conversas recentes',context:'Contexto',useContext:'Usar contexto desta tela',socratic:'Modo Socrático',minimize:'Minimizar',maximize:'Maximizar',restore:'Restaurar',close:'Fechar',
    greeting:'Olá! Sou seu tutor contextual de ECG. Posso orientar seu raciocínio sem tirar você da atividade que está fazendo.',noContext:'Estudo geral de ECG',thinking:'Analisando…',voice:'Entrada por voz',voiceUnsupported:'O reconhecimento de voz não é suportado por este navegador.',
    lockedTitle:'Tutor disponível após finalizar o simulado',lockedBody:'Este simulado está no Modo Prova. Para preservar a validade do resultado, o Tutor fica bloqueado até a finalização.',studyMode:'Modo estudo',examMode:'Modo prova',modeHelp:'No Modo estudo o Tutor fica disponível. No Modo prova ele é bloqueado até a finalização.',
    preAnswer:'Posso ajudar você a chegar à resposta sem revelá-la antes da tentativa. Comece por frequência e regularidade; depois avalie onda P, relação P:QRS, intervalo PR e largura do QRS. O que você percebe?',
    demo:'As respostas por IA exigem Supabase e a Edge Function ecg-tutor. Ainda posso orientar usando o contexto educacional atual.',genericGuide:'Use uma sequência sistemática: frequência → regularidade → onda P → PR → QRS → ST-T → conclusão. Diga o que você observa em cada etapa e eu ajudo a refinar seu raciocínio.',
    error:'Não consegui acessar o tutor: ',newTitle:'Nova conversa',privacy:'A voz é transcrita no navegador; o ECG Lab não armazena o áudio bruto.',
    qTrain:['Ajude-me a interpretar este ECG','Qual alteração devo procurar?','Explique este ritmo','Me dê uma dica'],
    qQuestion:['Me dê uma dica','Explique o conceito','Como devo raciocinar?','Por que minha resposta está errada?'],
    qCase:['Ajude no raciocínio clínico','Quais dados são mais importantes?','O que devo avaliar primeiro?','Analise meu raciocínio'],
    qStudy:['Explique de forma simples','Aprofunde este assunto','Faça uma analogia','Crie uma questão sobre isso'],
    qGeneric:['Explique um conceito','Faça uma pergunta de ECG para mim','Revise um ritmo comigo']
  };
  const safe=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>state?.user?.id||(state?.demo?'demo-user':'guest');
  const convKey=()=>CONV_PREFIX+uid(),signalKey=()=>SIGNAL_PREFIX+uid(),modeKey=()=>MODE_PREFIX+uid();
  const uuid=()=>crypto?.randomUUID?.()||`tutor-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  function readJson(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}}
  function writeJson(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
  function store(){const x=readJson(convKey(),null);return x&&Array.isArray(x.conversations)?x:{activeId:null,conversations:[]}}
  function saveStore(x){x.conversations=(x.conversations||[]).slice(0,20);writeJson(convKey(),x)}
  function activeConversation(create=true){const s=store();let c=s.conversations.find(x=>x.id===(ui.activeId||s.activeId));if(!c&&create){const now=new Date().toISOString();c={id:uuid(),title:T().newTitle,created_at:now,updated_at:now,messages:[]};s.conversations.unshift(c);s.activeId=c.id;ui.activeId=c.id;saveStore(s)}else if(c)ui.activeId=c.id;return c}
  function mutateConversation(fn){const s=store();let c=s.conversations.find(x=>x.id===(ui.activeId||s.activeId));if(!c){activeConversation(true);return mutateConversation(fn)}fn(c);c.updated_at=new Date().toISOString();s.activeId=c.id;s.conversations=[c,...s.conversations.filter(x=>x.id!==c.id)].slice(0,20);saveStore(s)}
  function addMessage(role,text,meta={}){mutateConversation(c=>{c.messages=(c.messages||[]).concat({role,text:String(text),at:new Date().toISOString(),...meta}).slice(-80);if((c.title===T().newTitle||c.title==='New conversation'||c.title==='Nova conversa')&&role==='user')c.title=String(text).replace(/\s+/g,' ').slice(0,52)})}
  function startNew(){const s=store(),now=new Date().toISOString(),c={id:uuid(),title:T().newTitle,created_at:now,updated_at:now,messages:[]};s.activeId=c.id;s.conversations.unshift(c);ui.activeId=c.id;saveStore(s);ui.history=false;render()}
  function openConversation(id){const s=store(),c=s.conversations.find(x=>x.id===id);if(!c)return;s.activeId=id;ui.activeId=id;saveStore(s);ui.history=false;render()}
  function signals(){const x=readJson(signalKey(),[]);return Array.isArray(x)?x:[]}
  function recordSignal(kind,ctx){const row={id:uuid(),created_at:new Date().toISOString(),user_id:uid(),help_type:kind,activity_type:ctx.activityType||'general',activity_id:ctx.activityId||null,question_id:ctx.questionId||null,topic:ctx.topic||null,category:ctx.category||null,answer_submitted:!!ctx.answerSubmitted,socratic:!!ui.socratic};const a=signals();a.unshift(row);writeJson(signalKey(),a.slice(0,300));window.dispatchEvent(new CustomEvent('ecg:tutor-signal',{detail:row}));if(typeof sb!=='undefined'&&sb&&state?.user&&!state?.demo)void sb.from('tutor_learning_signals').insert(row).then(({error})=>{if(error)console.warn('Tutor signal sync:',error.message)});return row}
  const currentModePreference=()=>localStorage.getItem(modeKey())||'exam';
  const setModePreference=v=>localStorage.setItem(modeKey(),v==='study'?'study':'exam');
  const sessions=prefix=>readJson(prefix+uid(),[]);
  const latestActive=prefix=>sessions(prefix).filter(s=>s?.status==='in_progress').sort((a,b)=>new Date(b.updated_at||b.created_at)-new Date(a.updated_at||a.created_at))[0]||null;
  const optionLabels=q=>(q?.options||[]).map(o=>Array.isArray(o)?String(o[0]):String(o?.label??o));
  function correctLabel(q){const o=(q?.options||[]).find(x=>Array.isArray(x)?!!x[1]:!!x?.is_correct);return o?(Array.isArray(o)?String(o[0]):String(o.label||'')):null}
  function studyRef(){const d=window.ECG_STUDY_CONTENT||{},lesson=state?.studyLessonKey?d.lessons?.[state.studyLessonKey]:null,c=lesson&&state?.studyCaseId?(lesson.cases||[]).find(x=>String(x.id)===String(state.studyCaseId)):null;return {lesson,c}}
  function performanceMemory(){const ev=readJson(`ecgLabPerformance:v1:${uid()}`,[]);if(!Array.isArray(ev))return null;const g={};for(const e of ev){const k=e?.metadata?.category||e?.subtopic||e?.competency;if(!k)continue;const x=g[k]||(g[k]={n:0,errors:0});x.n++;if(e.activity_type==='clinical_case'?Number(e.score)<60:!e.correct)x.errors++}const weak=Object.entries(g).filter(([,x])=>x.errors>=3).sort((a,b)=>b[1].errors-a[1].errors).slice(0,3).map(([topic,x])=>({topic,errors:x.errors,attempts:x.n}));return weak.length?weak:null}
  function trainingContext(){
    if(state?.page!=='treinar')return null;
    if(document.querySelector('.cat-runner')){const s=latestActive('ecgLabTraining:v1:');if(s){const qid=String(s.current_question_id||''),snap=s.current_question_snapshot||{},ans=(s.answers||[]).find(a=>String(a.question_id)===qid),submitted=!!ans;return {activityType:'quick_training',activityId:s.id,currentModule:'ECG Training',questionId:qid,questionText:snap.prompt||'',alternatives:(snap.options||[]).map(o=>o.label),selectedAnswer:submitted?snap.options?.[ans.selected_answer]?.label:null,answerSubmitted:submitted,correctAnswer:submitted?snap.options?.[ans.correct_answer]?.label:null,explanation:submitted?snap.explanation:null,ecgData:{imageUrl:snap.image_url||'',lead:'II',synthetic:true},topic:snap.category||'',category:snap.category||'',difficulty:snap.difficulty||null,sessionProgress:{current:(s.answers||[]).length+1,total:s.total_questions},label:`${isEn()?'ECG Training':'Treino ECG'} • ${isEn()?'Question':'Questão'} ${(s.answers||[]).length+1}/${s.total_questions}`}}
    }
    if(document.querySelector('#treinar .training,#treinar .adaptive-panel')){const q=typeof currentAdaptiveQuestion==='function'?currentAdaptiveQuestion():null,ecg=q&&typeof caseById==='function'?caseById(q.ecg_case_id):null,submitted=!!state?.adaptive?.answeredCurrent;if(q)return {activityType:'quick_training',activityId:'adaptive-live',currentModule:'ECG Training',questionId:String(q.id),questionText:q.prompt||'',alternatives:optionLabels(q),selectedAnswer:Number.isInteger(state?.selectedAnswer)?optionLabels(q)[state.selectedAnswer]:null,answerSubmitted:submitted,correctAnswer:submitted?correctLabel(q):null,explanation:submitted?(q.explanation||ecg?.explanation||null):null,ecgData:{imageUrl:ecg?.image_url||'',lead:'II',synthetic:true},topic:q.category||ecg?.category||'',category:q.category||ecg?.category||'',difficulty:q.difficulty||ecg?.difficulty||null,sessionProgress:{current:(state?.adaptive?.answered||0)+1,total:null},label:`${isEn()?'ECG Training':'Treino ECG'} • ${isEn()?'Question':'Questão'} ${(state?.adaptive?.answered||0)+1}`}}
    return {activityType:'training_home',currentModule:'ECG Training',answerSubmitted:true,label:isEn()?'ECG Training':'Treino ECG'};
  }
  function simulationContext(){
    if(state?.page!=='simulados')return null;const s=latestActive('ecgLabSimulations:v4:');
    if(!s||!document.querySelector('#simulados .sim-runner,#simulados [data-sim-answer],#simulados .sim-question-shell'))return {activityType:'simulation_home',currentModule:'Practice Exams',answerSubmitted:true,label:isEn()?'Practice Exams':'Simulados'};
    const idx=Number(s.current_question_index)||0,qid=String((s.question_ids||[])[idx]||''),snap=s.question_snapshots?.[qid]||{},a=s.answers?.[qid],submitted=Number.isInteger(a?.selected_answer),mode=s.tutor_mode||'exam';
    return {activityType:'simulation',activityId:s.id,currentModule:'Practice Exams',questionId:qid,questionText:snap.prompt||'',alternatives:(snap.options||[]).map(o=>o.label),selectedAnswer:submitted?snap.options?.[a.selected_answer]?.label:null,answerSubmitted:submitted,correctAnswer:submitted&&mode==='study'?snap.options?.find(o=>o.correct)?.label:null,explanation:submitted&&mode==='study'?snap.explanation:null,ecgData:{imageUrl:snap.image_url||'',lead:'II',synthetic:true},topic:snap.category||'',category:snap.category||'',difficulty:snap.difficulty||null,sessionProgress:{current:idx+1,total:s.total_questions},examMode:mode,locked:mode==='exam'&&s.status==='in_progress',label:`${isEn()?'Practice Exam':'Simulado'} • ${isEn()?'Question':'Questão'} ${idx+1}/${s.total_questions}`};
  }
  function studyContext(){
    if(state?.page!=='trilha')return null;const {lesson,c}=studyRef();
    if(c){const answer=document.getElementById('caseAnswer'),revealed=!!answer&&!answer.classList.contains('hidden');return {activityType:'clinical_case',activityId:state.studyLessonKey,caseId:c.id,currentModule:'Study Path',caseData:{title:c.title,chiefComplaint:c.chief_complaint,anamnesis:c.anamnesis,medications:c.medications,vitals:c.vitals,physicalExam:c.physical_exam,labs:c.labs,imaging:c.imaging,question:c.question,ecgImage:c.ecg_image},answerSubmitted:revealed,correctAnswer:revealed?c.answer:null,explanation:revealed?c.reasoning:null,topic:lesson?.title||'',difficulty:c.difficulty||null,ecgData:{imageUrl:c.ecg_image||'',lead:'II',synthetic:true},label:`${isEn()?'Clinical Case':'Estudo de Caso'} • ${c.title}`}}
    if(lesson)return {activityType:'study_lesson',activityId:state.studyLessonKey,currentModule:'Study Path',answerSubmitted:true,topic:lesson.title,lesson:{title:lesson.title,summary:lesson.summary,objectives:lesson.objectives},label:`${isEn()?'Study Path':'Trilha de Estudos'} • ${lesson.title}`};
    return {activityType:'study_home',currentModule:'Study Path',answerSubmitted:true,label:isEn()?'Study Path':'Trilha de Estudos'};
  }
  function buildContext(){const c=trainingContext()||simulationContext()||studyContext()||{activityType:state?.page||'general',currentModule:state?.page||'ECG Lab',answerSubmitted:true,label:T().noContext};c.language=window.ECG_LANG||'pt-BR';c.performanceMemory=performanceMemory();return c}
  function quickActions(ctx){if(ctx.activityType==='clinical_case')return T().qCase;if(ctx.activityType==='study_lesson')return T().qStudy;if(ctx.activityType==='quick_training')return ctx.answerSubmitted?T().qQuestion:T().qTrain;if(ctx.activityType==='simulation')return ctx.answerSubmitted?T().qQuestion:T().qQuestion.slice(0,3);return T().qGeneric}
  const revealIntent=text=>/\b(qual (é|e) a resposta|qual alternativa|resposta correta|me diga a resposta|correct answer|which option|give me the answer|what is the answer)\b/i.test(text);
  function helpKind(text){if(/dica|hint/i.test(text))return'hint';if(/errad|wrong/i.test(text))return'error_review';if(/racioc|reason/i.test(text))return'reasoning';if(/interpret|analys|analis/i.test(text))return'interpretation';return'concept'}
  function sanitizeContext(c){const x=JSON.parse(JSON.stringify(c||{}));if(!x.answerSubmitted){delete x.correctAnswer;delete x.explanation}return x}
  function root(){let r=document.getElementById('floatingTutorRoot');if(!r){r=document.createElement('div');r.id='floatingTutorRoot';document.body.appendChild(r)}return r}
  function removeLegacyTutor(){document.querySelectorAll('[data-page="tutor"]').forEach(n=>n.remove());document.getElementById('tutor')?.remove();if(state?.page==='tutor'){state.page='dashboard';try{window.__floatingTutorOriginalShow?.('dashboard')}catch{}}}
  function renderMessages(){const c=activeConversation(true),log=document.getElementById('floatingTutorLog');if(!log)return;const msgs=c?.messages||[];log.innerHTML=msgs.length?msgs.map(m=>`<div class="ft-msg ${m.role==='user'?'user':'bot'}"><div>${safe(m.text).replace(/\n/g,'<br>')}</div><small>${new Intl.DateTimeFormat(isEn()?'en-US':'pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(m.at))}</small></div>`).join(''):`<div class="ft-msg bot"><div>${safe(T().greeting)}</div></div>`;if(ui.thinking)log.insertAdjacentHTML('beforeend',`<div class="ft-msg bot thinking"><span></span><span></span><span></span><em>${safe(T().thinking)}</em></div>`);log.scrollTop=log.scrollHeight}
  function renderHistory(){const s=store(),box=document.getElementById('floatingTutorHistory');if(!box)return;box.innerHTML=`<div class="ft-history-head"><strong>${safe(T().recent)}</strong><button id="ftHistoryClose">×</button></div><button class="btn btn-primary full" id="ftNewConversation">${safe(T().newChat)}</button><div class="ft-history-list">${(s.conversations||[]).map(c=>`<button data-ft-conv="${safe(c.id)}" class="${c.id===ui.activeId?'active':''}"><strong>${safe(c.title||T().newTitle)}</strong><small>${new Intl.DateTimeFormat(isEn()?'en-US':'pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(c.updated_at||c.created_at))}</small></button>`).join('')||`<p class="muted">${safe(T().newTitle)}</p>`}</div>`;box.classList.toggle('show',ui.history);document.getElementById('ftHistoryClose').onclick=()=>{ui.history=false;box.classList.remove('show')};document.getElementById('ftNewConversation').onclick=startNew;box.querySelectorAll('[data-ft-conv]').forEach(b=>b.onclick=()=>openConversation(b.dataset.ftConv))}
  function render(){
    removeLegacyTutor();const r=root(),ctx=buildContext(),locked=!!ctx.locked,actions=quickActions(ctx);document.body.classList.toggle('tutor-panel-open',ui.open&&!locked);document.body.style.setProperty('--floating-tutor-width',`${ui.width}px`);
    r.innerHTML=`<button id="floatingTutorFab" class="ft-fab ${ui.open?'open':''} ${locked?'locked':''}" aria-label="${safe(T().name)}"><span>✦</span><b>${safe(T().name)}</b>${activeConversation(false)?.messages?.length?'<i></i>':''}${locked?'<em>🔒</em>':''}</button>
    <aside id="floatingTutorPanel" class="ft-panel ${ui.open?'show':''} ${ui.max?'max':''} sheet-${ui.sheet}" aria-hidden="${ui.open?'false':'true'}"><div class="ft-resize" id="ftResize"></div><div class="ft-sheet-handle" id="ftSheetHandle"><span></span></div>
    <header class="ft-head"><div><span class="ft-ai-mark">✦</span><div><strong>${safe(T().brand)}</strong><small id="ftContextLabel">${safe(T().context)}: ${safe(ctx.label||T().noContext)}</small></div></div><nav><button id="ftHistoryBtn" title="${safe(T().recent)}">☰</button><button id="ftMinBtn" title="${safe(T().minimize)}">—</button><button id="ftMaxBtn" title="${safe(ui.max?T().restore:T().maximize)}">${ui.max?'❐':'□'}</button><button id="ftCloseBtn" title="${safe(T().close)}">×</button></nav></header>
    ${locked?`<section class="ft-locked"><div>🔒</div><h3>${safe(T().lockedTitle)}</h3><p>${safe(T().lockedBody)}</p><small>${safe(ctx.label)}</small></section>`:`<div class="ft-controls"><label><input id="ftUseContext" type="checkbox" ${ui.useContext?'checked':''}> ${safe(T().useContext)}</label><label><input id="ftSocratic" type="checkbox" ${ui.socratic?'checked':''}> ${safe(T().socratic)}</label></div><div class="ft-actions">${actions.map(a=>`<button data-ft-quick="${safe(a)}">${safe(a)}</button>`).join('')}</div><div class="ft-chat" id="floatingTutorLog"></div><footer class="ft-compose"><textarea id="floatingTutorInput" placeholder="${safe(T().ask)}" rows="1"></textarea><button id="ftVoiceBtn" title="${safe(T().voice)}">🎙️</button><button id="floatingTutorSend" class="btn btn-primary" aria-label="${safe(T().send)}">➤</button></footer><div class="ft-privacy">${safe(T().privacy)}</div>`}<section id="floatingTutorHistory" class="ft-history"></section></aside>`;
    document.getElementById('floatingTutorFab').onclick=()=>{ui.open=!ui.open;if(ui.open)ui.sheet='mid';render()};
    document.getElementById('ftMinBtn')?.addEventListener('click',()=>{ui.open=false;render()});document.getElementById('ftCloseBtn')?.addEventListener('click',()=>{ui.open=false;render()});document.getElementById('ftMaxBtn')?.addEventListener('click',()=>{ui.max=!ui.max;ui.sheet=ui.max?'full':'mid';render()});document.getElementById('ftHistoryBtn')?.addEventListener('click',()=>{ui.history=!ui.history;renderHistory()});
    document.getElementById('ftUseContext')?.addEventListener('change',e=>{ui.useContext=!!e.target.checked;localStorage.setItem('ecgLabTutorUseContext',ui.useContext?'1':'0')});document.getElementById('ftSocratic')?.addEventListener('change',e=>{ui.socratic=!!e.target.checked;localStorage.setItem('ecgLabTutorSocratic',ui.socratic?'1':'0')});
    document.getElementById('floatingTutorSend')?.addEventListener('click',send);document.getElementById('floatingTutorInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});document.getElementById('ftVoiceBtn')?.addEventListener('click',startVoice);r.querySelectorAll('[data-ft-quick]').forEach(b=>b.onclick=()=>{const inp=document.getElementById('floatingTutorInput');if(inp){inp.value=b.dataset.ftQuick;send()}});bindResize();bindSheetDrag();renderMessages();renderHistory();syncModeChooser();
  }
  async function send(){if(ui.thinking)return;const inp=document.getElementById('floatingTutorInput'),text=inp?.value.trim();if(!text)return;const ctx=buildContext();if(ctx.locked)return;addMessage('user',text,{context:ctx.label});recordSignal(helpKind(text),ctx);inp.value='';renderMessages();if(ui.useContext&&!ctx.answerSubmitted&&revealIntent(text)){addMessage('assistant',T().preAnswer,{guard:'pre-answer'});renderMessages();return}if(typeof sb==='undefined'||!sb||!state?.user||state?.demo){const reply=ui.useContext&&!ctx.answerSubmitted?T().preAnswer:`${T().demo} ${T().genericGuide}`;setTimeout(()=>{addMessage('assistant',reply,{demo:true});renderMessages()},220);return}ui.thinking=true;renderMessages();try{const {data:{session}}=await sb.auth.getSession(),c=activeConversation(false),history=(c?.messages||[]).slice(-10,-1).map(m=>({role:m.role==='assistant'?'assistant':'user',content:m.text})),payload={message:text,language:window.ECG_LANG||'pt-BR',socratic_mode:ui.socratic,history,context:ui.useContext?sanitizeContext(ctx):null};const res=await fetch(`${CFG.SUPABASE_URL}/functions/v1/ecg-tutor`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify(payload)}),data=await res.json();if(!res.ok)throw new Error(data.error||(isEn()?'Tutor request failed':'Falha no Tutor'));addMessage('assistant',data.reply||(isEn()?'No response was returned.':'Nenhuma resposta foi retornada.'),{context:ctx.label})}catch(e){addMessage('assistant',T().error+(e?.message||String(e)),{error:true})}finally{ui.thinking=false;renderMessages()}}
  function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast?.(T().voiceUnsupported);return}if(ui.recognition){try{ui.recognition.stop()}catch{}ui.recognition=null;return}const r=new SR();ui.recognition=r;r.lang=isEn()?'en-US':'pt-BR';r.interimResults=false;r.continuous=false;const b=document.getElementById('ftVoiceBtn');if(b){b.classList.add('listening');b.textContent='●'}r.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'',inp=document.getElementById('floatingTutorInput');if(inp){inp.value=text;inp.focus()}};r.onerror=()=>toast?.(T().voiceUnsupported);r.onend=()=>{ui.recognition=null;const x=document.getElementById('ftVoiceBtn');if(x){x.classList.remove('listening');x.textContent='🎙️'}};r.start()}
  function bindResize(){const h=document.getElementById('ftResize');if(!h)return;h.onpointerdown=e=>{if(innerWidth<=720)return;h.setPointerCapture?.(e.pointerId);const start=e.clientX,w=ui.width,move=ev=>{ui.width=Math.max(360,Math.min(Math.round(innerWidth*.42),w+(start-ev.clientX)));document.body.style.setProperty('--floating-tutor-width',`${ui.width}px`)},up=()=>{h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',up)};h.addEventListener('pointermove',move);h.addEventListener('pointerup',up)}}
  function bindSheetDrag(){const h=document.getElementById('ftSheetHandle');if(!h)return;h.onpointerdown=e=>{if(innerWidth>720)return;h.setPointerCapture?.(e.pointerId);const y=e.clientY,up=ev=>{const d=ev.clientY-y;if(d>90)ui.open=false;else if(d<-70){ui.sheet='full';ui.max=true}else if(Math.abs(d)<30&&ui.sheet==='full'){ui.sheet='mid';ui.max=false}render();h.removeEventListener('pointerup',up)};h.addEventListener('pointerup',up)}}
  function syncModeChooser(){const modal=document.querySelector('#simModalRoot .sim-new-modal');if(!modal||modal.querySelector('.ft-exam-mode'))return;const actions=modal.querySelector('.sim-modal-actions');if(!actions)return;const pref=currentModePreference(),wrap=document.createElement('div');wrap.className='ft-exam-mode';wrap.innerHTML=`<div><strong>${safe(T().studyMode)} / ${safe(T().examMode)}</strong><small>${safe(T().modeHelp)}</small></div><div class="ft-segment"><button type="button" data-ft-mode="study" class="${pref==='study'?'active':''}">${safe(T().studyMode)}</button><button type="button" data-ft-mode="exam" class="${pref==='exam'?'active':''}">${safe(T().examMode)}</button></div>`;actions.before(wrap);wrap.querySelectorAll('[data-ft-mode]').forEach(b=>b.onclick=()=>{setModePreference(b.dataset.ftMode);wrap.querySelectorAll('[data-ft-mode]').forEach(x=>x.classList.toggle('active',x.dataset.ftMode===b.dataset.ftMode))})}
  function patchSimulationStorage(){if(window.__floatingTutorStoragePatch||!window.Storage)return;const orig=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(this===localStorage&&String(key).startsWith('ecgLabSimulations:v4:')){try{const list=JSON.parse(value);if(Array.isArray(list)){let changed=false;for(const s of list){if(s&&s.status==='in_progress'&&!s.tutor_mode){s.tutor_mode=currentModePreference();changed=true}}if(changed)value=JSON.stringify(list)}}catch{}}return orig.call(this,key,value)};window.__floatingTutorStoragePatch=true}
  function patchNavigation(){if(!window.__floatingTutorOriginalShow&&typeof showPage==='function'){window.__floatingTutorOriginalShow=showPage;window.showPage=function(id){if(id==='tutor'){ui.open=true;render();return}const r=window.__floatingTutorOriginalShow(id);setTimeout(render,0);return r}}if(!window.__floatingTutorOriginalShell&&typeof shell==='function'){window.__floatingTutorOriginalShell=shell;window.shell=function(){const r=window.__floatingTutorOriginalShell();setTimeout(render,0);return r}}}
  function boot(){ui.useContext=localStorage.getItem('ecgLabTutorUseContext')!=='0';ui.socratic=localStorage.getItem('ecgLabTutorSocratic')==='1';patchSimulationStorage();patchNavigation();removeLegacyTutor();activeConversation(true);render();const mo=new MutationObserver(()=>{removeLegacyTutor();syncModeChooser();const label=document.getElementById('ftContextLabel');if(label)label.textContent=`${T().context}: ${buildContext().label||T().noContext}`});mo.observe(document.body,{subtree:true,childList:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else setTimeout(boot,0);
  window.ECG_TUTOR={open:()=>{ui.open=true;render()},close:()=>{ui.open=false;render()},newConversation:startNew,getContext:buildContext,getLearningSignals:signals,setPracticeMode:setModePreference};
})();