/* ECG Lab — 20 progressive Ischemia/ST-T cases with synthetic 12-lead ECGs.
   Educational only. Tracings are generated in-browser so the lesson does not depend on external image files. */
(function(){
  'use strict';

  const LEADS=['I','aVR','V1','V4','II','aVL','V2','V5','III','aVF','V3','V6'];
  const BASE={
    I:{pol:1,amp:15,t:6},aVR:{pol:-1,amp:13,t:-5},V1:{pol:-1,amp:12,t:3},V4:{pol:1,amp:20,t:8},
    II:{pol:1,amp:18,t:7},aVL:{pol:1,amp:10,t:5},V2:{pol:1,amp:12,t:7},V5:{pol:1,amp:19,t:8},
    III:{pol:1,amp:11,t:5},aVF:{pol:1,amp:14,t:6},V3:{pol:1,amp:17,t:8},V6:{pol:1,amp:15,t:7}
  };
  const P={
    isch01:{II:{st:8},III:{st:12},aVF:{st:10},I:{st:-4},aVL:{st:-7}},
    isch02:{V1:{st:5},V2:{st:12},V3:{st:15},V4:{st:12},V5:{st:5},III:{st:-4},aVF:{st:-5}},
    isch03:{I:{st:7},aVL:{st:8},V3:{st:10},V4:{st:13},V5:{st:11},V6:{st:8},III:{st:-4},aVF:{st:-5}},
    isch04:{I:{st:9},aVL:{st:11},III:{st:-6},aVF:{st:-5}},
    isch05:{II:{st:9},III:{st:13},aVF:{st:11},V1:{st:7,pol:1},I:{st:-4},aVL:{st:-7}},
    isch06:{V1:{st:-8,morph:'tallR',pol:1,amp:22,t:8},V2:{st:-11,morph:'tallR',pol:1,amp:24,t:10},V3:{st:-8,morph:'tallR',pol:1,amp:22,t:9}},
    isch07:{I:{st:-4,t:-6},aVL:{st:-5,t:-7},V4:{st:-5,t:-5},V5:{st:-8,t:-8},V6:{st:-7,t:-8}},
    isch08:{all:{st:-5},aVR:{st:7,t:4},V1:{st:2},I:{st:-6},II:{st:-7},III:{st:-5},aVL:{st:-6},aVF:{st:-6},V3:{st:-7},V4:{st:-8},V5:{st:-8},V6:{st:-7}},
    isch09:{V2:{t:-14},V3:{t:-16},V4:{t:-13},V5:{t:-8}},
    isch10:{V2:{tType:'biphasic',t:13},V3:{tType:'biphasic',t:14},V4:{tType:'biphasic',t:9}},
    isch11:{aVR:{st:4,t:4},V2:{st:-7,tType:'peaked',t:17},V3:{st:-8,tType:'peaked',t:19},V4:{st:-8,tType:'peaked',t:19},V5:{st:-7,tType:'peaked',t:17},V6:{st:-5,tType:'peaked',t:15}},
    isch12:{V2:{st:3,tType:'broad',t:16},V3:{st:4,tType:'broad',t:18},V4:{st:3,tType:'broad',t:17},III:{st:-2},aVF:{st:-3}},
    isch13:{V2:{st:4,t:10,jNotch:true},V3:{st:6,t:11,jNotch:true},V4:{st:6,t:11,jNotch:true},V5:{st:4,t:9,jNotch:true}},
    isch14:{all:{st:5},aVR:{st:-5,t:-4},V1:{st:-2,t:2},I:{st:5},II:{st:6},aVL:{st:4},aVF:{st:5},V2:{st:5},V3:{st:6},V4:{st:6},V5:{st:5},V6:{st:4}},
    isch15:{I:{morph:'highPos',amp:24,st:-5,t:-8},aVL:{morph:'highPos',amp:23,st:-6,t:-9},V5:{morph:'highPos',amp:30,st:-8,t:-11},V6:{morph:'highPos',amp:28,st:-7,t:-10},V1:{morph:'highNeg',amp:27,st:4,t:5},V2:{morph:'highNeg',amp:25,st:3,t:4}},
    isch16:{I:{morph:'lbbbPos',st:-4,t:-7},aVL:{morph:'lbbbPos',st:-4,t:-7},V5:{morph:'lbbbPos',st:-6,t:-9},V6:{morph:'lbbbPos',st:-6,t:-9},V1:{morph:'lbbbNeg',st:6,t:7},V2:{morph:'lbbbNeg',st:5,t:7},V3:{morph:'lbbbNeg',st:4,t:6},II:{morph:'lbbbPos',st:-3,t:-6},III:{morph:'lbbbPos',st:-2,t:-5},aVF:{morph:'lbbbPos',st:-3,t:-5},aVR:{morph:'lbbbNeg',st:3,t:4},V4:{morph:'lbbbPos',st:-4,t:-7}},
    isch17:{V1:{morph:'qs',amp:18,st:5,t:2},V2:{morph:'qs',amp:22,st:8,t:3},V3:{morph:'qs',amp:24,st:8,t:3},V4:{morph:'qs',amp:20,st:6,t:3}},
    isch18:{I:{t:-7},II:{t:-8},aVL:{t:-7},aVF:{t:-7},V2:{t:-10},V3:{t:-13},V4:{t:-15},V5:{t:-13},V6:{t:-10}},
    isch19:{II:{st:-3,tType:'flat',u:5},aVL:{st:-2,tType:'flat',u:4},aVF:{st:-3,tType:'flat',u:4},V2:{st:-3,tType:'flat',u:6},V3:{st:-4,tType:'flat',u:7},V4:{st:-4,tType:'flat',u:7},V5:{st:-3,tType:'flat',u:6},V6:{st:-2,tType:'flat',u:5}},
    isch20:{all:{tType:'peaked',t:16,morph:'mildWide'},aVR:{tType:'peaked',t:-12,morph:'mildWide'},V1:{tType:'peaked',t:13,morph:'mildWide'},V2:{tType:'peaked',t:17,morph:'mildWide'},V3:{tType:'peaked',t:18,morph:'mildWide'},V4:{tType:'peaked',t:18,morph:'mildWide'},V5:{tType:'peaked',t:17,morph:'mildWide'},V6:{tType:'peaked',t:15,morph:'mildWide'}}
  };

  function n(v){return Number(v.toFixed(1));}
  function pathFor(lead,cfg){
    const b=70, beat=76, base=Object.assign({},BASE[lead]||BASE.II,cfg||{}), pol=base.pol==null?1:base.pol, amp=base.amp||16;
    let d=`M 4 ${b}`;
    for(let x=8;x<238;x+=beat){
      const p=3*pol;
      d+=` L ${x} ${b} C ${x+4} ${b} ${x+6} ${n(b-p)} ${x+10} ${n(b-p)} C ${x+14} ${n(b-p)} ${x+16} ${b} ${x+19} ${b}`;
      const q=x+25;
      if(base.morph==='qs'){
        d+=` L ${q} ${b} L ${q+5} ${n(b+amp)} L ${q+13} ${n(b+amp*.75)} L ${q+20} ${b}`;
      }else if(base.morph==='tallR'){
        d+=` L ${q} ${n(b+2)} L ${q+3} ${n(b-amp)} L ${q+7} ${n(b+5)} L ${q+12} ${b}`;
      }else if(base.morph==='highPos'){
        d+=` L ${q} ${n(b+4)} L ${q+3} ${n(b-amp)} L ${q+7} ${n(b+amp*.28)} L ${q+11} ${b}`;
      }else if(base.morph==='highNeg'){
        d+=` L ${q} ${n(b-3)} L ${q+4} ${n(b+amp)} L ${q+9} ${n(b-4)} L ${q+13} ${b}`;
      }else if(base.morph==='lbbbPos'){
        d+=` L ${q} ${n(b+3)} C ${q+3} ${n(b-15)} ${q+7} ${n(b-22)} ${q+12} ${n(b-18)} C ${q+16} ${n(b-25)} ${q+21} ${n(b-20)} ${q+25} ${b}`;
      }else if(base.morph==='lbbbNeg'){
        d+=` L ${q} ${n(b-3)} C ${q+4} ${n(b+12)} ${q+8} ${n(b+24)} ${q+14} ${n(b+22)} C ${q+19} ${n(b+26)} ${q+23} ${n(b+15)} ${q+26} ${b}`;
      }else if(base.morph==='mildWide'){
        d+=` L ${q} ${n(b+2*pol)} L ${q+4} ${n(b-amp*.8*pol)} L ${q+10} ${n(b+amp*.3*pol)} L ${q+16} ${b}`;
      }else{
        d+=` L ${q} ${n(b+3*pol)} L ${q+3} ${n(b-amp*pol)} L ${q+7} ${n(b+amp*.28*pol)} L ${q+11} ${b}`;
      }
      const qrsEnd=(base.morph==='lbbbPos'||base.morph==='lbbbNeg')?q+26:(base.morph==='mildWide'?q+16:(base.morph==='qs'?q+20:(base.morph==='tallR'||base.morph==='highPos'?q+12:(base.morph==='highNeg'?q+13:q+11))));
      const st=base.st||0, sy=n(b-st), sx=qrsEnd;
      if(base.jNotch){d+=` L ${sx+2} ${n(sy-2)} L ${sx+4} ${sy}`;}
      d+=` L ${sx+13} ${sy}`;
      const tx=sx+25, tv=base.t==null?(BASE[lead]?.t||6):base.t;
      if(base.tType==='biphasic'){
        d+=` C ${tx-6} ${sy} ${tx-4} ${n(b-tv*.65)} ${tx} ${n(b-tv*.65)} C ${tx+4} ${n(b-tv*.65)} ${tx+5} ${n(b+tv*.8)} ${tx+9} ${n(b+tv*.8)} C ${tx+13} ${n(b+tv*.8)} ${tx+15} ${b} ${tx+19} ${b}`;
      }else if(base.tType==='peaked'){
        d+=` C ${tx-7} ${sy} ${tx-3} ${n(b-tv*.35)} ${tx} ${n(b-tv)} C ${tx+3} ${n(b-tv*.35)} ${tx+7} ${b} ${tx+12} ${b}`;
      }else if(base.tType==='broad'){
        d+=` C ${tx-9} ${sy} ${tx-5} ${n(b-tv)} ${tx+2} ${n(b-tv)} C ${tx+9} ${n(b-tv)} ${tx+13} ${b} ${tx+18} ${b}`;
      }else{
        const tval=base.tType==='flat'?(tv>=0?1.2:-1.2):tv;
        d+=` C ${tx-8} ${sy} ${tx-5} ${n(b-tval)} ${tx+1} ${n(b-tval)} C ${tx+7} ${n(b-tval)} ${tx+11} ${b} ${tx+17} ${b}`;
      }
      if(base.u){const ux=tx+23;d+=` C ${ux} ${b} ${ux+3} ${n(b-base.u)} ${ux+6} ${n(b-base.u)} C ${ux+9} ${n(b-base.u)} ${ux+12} ${b} ${ux+15} ${b}`;}
      d+=` L ${x+beat-2} ${b}`;
    }
    return d;
  }

  function ecgDataUri(patternKey){
    const pat=P[patternKey]||{};
    const cellW=290,cellH=142,padX=22,padY=54;
    const cells=LEADS.map((lead,i)=>{
      const row=Math.floor(i/4),col=i%4,x=padX+col*cellW,y=padY+row*cellH;
      const cfg=Object.assign({},pat.all||{},pat[lead]||{});
      return `<g transform="translate(${x},${y})"><text x="2" y="15" font-size="13" font-family="system-ui,Arial" font-weight="700" fill="#334155">${lead}</text><path d="${pathFor(lead,cfg)}" fill="none" stroke="#0f172a" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"/></g>`;
    }).join('');
    const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 500" width="1200" height="500"><defs><pattern id="sm" width="6" height="6" patternUnits="userSpaceOnUse"><path d="M 6 0 L 0 0 0 6" fill="none" stroke="#e7ebf0" stroke-width="0.7"/></pattern><pattern id="lg" width="30" height="30" patternUnits="userSpaceOnUse"><rect width="30" height="30" fill="url(#sm)"/><path d="M 30 0 L 0 0 0 30" fill="none" stroke="#cbd5e1" stroke-width="1"/></pattern></defs><rect width="1200" height="500" fill="#ffffff"/><rect x="10" y="10" width="1180" height="470" rx="12" fill="url(#lg)"/><text x="24" y="34" font-size="14" font-family="system-ui,Arial" fill="#475569">12-lead ECG | 25 mm/s | 10 mm/mV | synthetic educational tracing</text>${cells}<g transform="translate(30,462)" stroke="#0f172a" stroke-width="1.8" fill="none"><path d="M 0 0 L 0 -20 L 12 -20 L 12 0 L 30 0"/></g></svg>`;
    return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);
  }

  const PT=[
    {id:'isch_stt_01',p:'isch01',title:'Dor torácica com náusea e sudorese',difficulty:1,chief_complaint:'Homem, 58 anos, com dor retroesternal intensa há 50 minutos, associada a náusea e sudorese.',anamnesis:'Hipertensão, dislipidemia e tabagismo. Dor em aperto, contínua, sem relação com posição ou respiração.',medications:'Losartana; atorvastatina de uso irregular.',vitals:'PA 148/92 mmHg • FC 78 bpm • FR 18 irpm • SpO₂ 97% em ar ambiente',physical_exam:['Pálido e diaforético, consciente e orientado.','Bulhas rítmicas; pulmões sem estertores.'],labs:['Troponina ultrassensível inicialmente acima do limite de referência.','K⁺ 4,2 mmol/L; creatinina sem alteração relevante.'],imaging:'Ecocardiograma à beira-leito com alteração segmentar inferior discreta.',question:'Qual padrão de ST-T está presente e qual território ele sugere?',answer:'Padrão de IAM com elevação do ST em território inferior.',reasoning:'Há elevação do ST em II, III e aVF, com depressão recíproca em I e aVL. A distribuição em derivações contíguas, os achados recíprocos e a clínica tornam o padrão compatível com oclusão coronariana aguda inferior.',trap:'A dor pode ser confundida com causa gastrointestinal; o ECG deve ser lido pela distribuição territorial, não pelo nome dado ao sintoma.',learning_point:'Supra em derivações contíguas com alterações recíprocas aumenta a coerência anatômica do diagnóstico.'},
    {id:'isch_stt_02',p:'isch02',title:'Dor precordial progressiva em paciente com diabetes',difficulty:2,chief_complaint:'Mulher, 64 anos, com dor precordial intensa há 90 minutos e sensação de fraqueza.',anamnesis:'Diabetes tipo 2, hipertensão e história familiar de doença coronariana precoce.',medications:'Metformina; anlodipino; rosuvastatina.',vitals:'PA 136/84 mmHg • FC 92 bpm • FR 20 irpm • SpO₂ 96%',physical_exam:['Ansiosa, perfusão periférica preservada.','Sem sinais de congestão pulmonar.'],labs:['Troponina ultrassensível em elevação na segunda coleta.','K⁺ 4,0 mmol/L.'],imaging:'Ecocardiograma com hipocinesia anterosseptal.',question:'Onde estão as alterações principais e qual síndrome eletrocardiográfica deve ser reconhecida?',answer:'Padrão de IAM com elevação do ST anterior.',reasoning:'O supra predomina em V2–V4, estendendo-se discretamente a V1/V5, com depressão recíproca inferior. O conjunto localiza a lesão aguda na parede anterior/anterosseptal.',trap:'Um traçado muito precoce pode ainda não apresentar ondas Q; a ausência de Q não exclui oclusão aguda.',learning_point:'V2–V4 são derivações-chave para reconhecer lesão anterior; sempre compare com derivações inferiores e traçados seriados.'},
    {id:'isch_stt_03',p:'isch03',title:'Dor torácica em repouso com irradiação para o braço',difficulty:2,chief_complaint:'Homem, 52 anos, com dor em aperto em repouso irradiada para braço esquerdo há 40 minutos.',anamnesis:'Tabagista, obesidade e sedentarismo. Sem ECG prévio disponível.',medications:'Nenhuma medicação cardiovascular regular.',vitals:'PA 154/96 mmHg • FC 88 bpm • FR 19 irpm • SpO₂ 98%',physical_exam:['Diaforese leve.','Ausculta cardíaca e pulmonar sem alterações relevantes.'],labs:['Troponina inicial discretamente elevada.','Eletrólitos dentro da faixa esperada.'],imaging:'Ecocardiograma com alteração segmentar anterior e lateral.',question:'A distribuição das alterações de ST envolve quais paredes?',answer:'Padrão de IAM com elevação do ST anterolateral.',reasoning:'Elevação do ST em I, aVL e V3–V6, com alterações recíprocas inferiores, forma um padrão anterolateral coerente.',trap:'Olhar apenas V3–V4 pode levar a classificar o traçado apenas como anterior e perder a extensão lateral.',learning_point:'Agrupe derivações por territórios e descreva a extensão do padrão em vez de interpretar cada derivação isoladamente.'},
    {id:'isch_stt_04',p:'isch04',title:'Pressão torácica com alterações discretas no ECG',difficulty:3,chief_complaint:'Mulher, 60 anos, com pressão torácica recorrente e sudorese, atualmente com dor leve.',anamnesis:'Dislipidemia e doença arterial periférica.',medications:'AAS em uso prévio; estatina.',vitals:'PA 142/86 mmHg • FC 82 bpm • FR 17 irpm • SpO₂ 97%',physical_exam:['Sem sinais de insuficiência cardíaca.','Pulsos periféricos palpáveis.'],labs:['Troponina ultrassensível com curva ascendente.','Hemoglobina 13,1 g/dL.'],imaging:'Ecocardiograma sem alteração global importante, com possível hipocinesia lateral focal.',question:'Que padrão territorial pode ser reconhecido mesmo com poucas derivações alteradas?',answer:'Padrão de lesão lateral alta.',reasoning:'A elevação do ST concentra-se em I e aVL, acompanhada de depressão recíproca em III/aVF. Esse padrão deve levantar suspeita de lesão lateral alta no contexto clínico adequado.',trap:'A pequena quantidade de derivações com supra pode fazer o achado parecer inespecífico.',learning_point:'Alterações focais em I/aVL ganham significado quando há reciprocidade inferior e sintomas compatíveis.'},
    {id:'isch_stt_05',p:'isch05',title:'Dor torácica, hipotensão e turgência jugular',difficulty:3,chief_complaint:'Homem, 67 anos, com dor torácica intensa, tontura e náusea.',anamnesis:'Hipertensão; sem insuficiência cardíaca conhecida.',medications:'Hidroclorotiazida; losartana.',vitals:'PA 86/58 mmHg • FC 64 bpm • FR 20 irpm • SpO₂ 95%',physical_exam:['Turgência jugular presente.','Pulmões limpos à ausculta; extremidades frias.'],labs:['Troponina ultrassensível elevada.','K⁺ 4,3 mmol/L.'],imaging:'Ecocardiograma focado sugere disfunção de ventrículo direito.',question:'Além do território inferior, qual extensão deve ser suspeitada e qual registro adicional ajudaria?',answer:'IAM inferior com suspeita de envolvimento do ventrículo direito; obter derivações direitas, especialmente V4R.',reasoning:'Há supra em II, III e aVF, depressão recíproca em I/aVL e elevação em V1. Hipotensão, turgência jugular e pulmões limpos reforçam a possibilidade de acometimento do ventrículo direito.',trap:'Interpretar V1 isoladamente como padrão anterior e ignorar o conjunto clínico-inferior.',learning_point:'No IAM inferior com hipotensão e pulmões limpos, procure envolvimento de VD e complemente com derivações direitas.'},
    {id:'isch_stt_06',p:'isch06',title:'Dor torácica com depressão anterior do ST',difficulty:4,chief_complaint:'Homem, 59 anos, com dor retroesternal e sudorese há 70 minutos.',anamnesis:'Tabagismo e diabetes. Dor persistente apesar de repouso.',medications:'Metformina; sinvastatina.',vitals:'PA 132/80 mmHg • FC 84 bpm • FR 18 irpm • SpO₂ 96%',physical_exam:['Sem congestão pulmonar.','Perfusão periférica preservada.'],labs:['Troponina ultrassensível em elevação.','K⁺ 4,4 mmol/L.'],imaging:'Derivações posteriores V7–V9, se obtidas, ajudam a confirmar a suspeita.',question:'A depressão do ST em V1–V3 representa apenas isquemia anterior?',answer:'Padrão recíproco sugestivo de infarto posterior.',reasoning:'Depressão horizontal do ST em V1–V3 associada a ondas R relativamente altas e T positivas pode ser a imagem em espelho de elevação posterior do ST. O contexto de dor aguda torna o padrão especialmente importante.',trap:'Rotular automaticamente toda depressão anterior de ST como isquemia subendocárdica anterior.',learning_point:'ST deprimido em V1–V3 + R alta + T positiva deve fazer pensar em parede posterior e motivar derivações V7–V9.'},
    {id:'isch_stt_07',p:'isch07',title:'Dispneia e pressão torácica aos esforços mínimos',difficulty:3,chief_complaint:'Mulher, 71 anos, com pressão torácica e dispneia ao caminhar poucos metros, pior nas últimas horas.',anamnesis:'Doença coronariana conhecida e diabetes.',medications:'AAS; atorvastatina; carvedilol.',vitals:'PA 150/88 mmHg • FC 96 bpm • FR 22 irpm • SpO₂ 95%',physical_exam:['Sem dor pleurítica.','Estertores ausentes; ritmo cardíaco regular.'],labs:['Troponina ultrassensível com elevação dinâmica.','Hb 12,4 g/dL; K⁺ 4,1 mmol/L.'],imaging:'Ecocardiograma com fração de ejeção preservada e alteração lateral sutil.',question:'Como interpretar a depressão horizontal do ST nas derivações laterais?',answer:'Isquemia subendocárdica lateral em contexto de síndrome coronariana aguda sem supra.',reasoning:'Depressão do ST em I, aVL e V4–V6, associada a alterações de T e biomarcador dinâmico, favorece isquemia subendocárdica. O ECG não deve ser interpretado isoladamente.',trap:'Considerar qualquer depressão de ST como “inespecífica” sem avaliar morfologia, distribuição, sintomas e evolução.',learning_point:'Na SCA sem supra, alterações seriadas de ST-T e troponina têm papel central na integração diagnóstica.'},
    {id:'isch_stt_08',p:'isch08',title:'Dor persistente com alterações difusas de ST',difficulty:4,chief_complaint:'Homem, 73 anos, com dor torácica opressiva persistente e dispneia.',anamnesis:'Doença coronariana multiarterial conhecida; hipertensão e diabetes.',medications:'AAS; estatina de alta intensidade; betabloqueador.',vitals:'PA 104/68 mmHg • FC 102 bpm • FR 24 irpm • SpO₂ 94%',physical_exam:['Pele fria; enchimento capilar discretamente lento.','Sem sopro novo evidente.'],labs:['Troponina ultrassensível significativamente elevada.','Lactato discretamente elevado.'],imaging:'Ecocardiograma com hipocinesia global leve.',question:'O que significa depressão difusa de ST associada a elevação em aVR?',answer:'Padrão de isquemia subendocárdica difusa de alto risco.',reasoning:'Depressão de ST em múltiplas derivações com elevação em aVR sugere isquemia subendocárdica global e pode ocorrer em doença coronariana extensa, tronco da coronária esquerda ou importante desequilíbrio oferta-demanda. O ECG não identifica sozinho uma anatomia específica.',trap:'Declarar “oclusão de tronco” como diagnóstico anatômico definitivo apenas pelo ECG.',learning_point:'Supra em aVR + depressão difusa é um padrão de alto risco, mas exige correlação clínica e anatômica; não é sinônimo de uma única lesão.'},
    {id:'isch_stt_09',p:'isch09',title:'Dor que cessou antes do ECG',difficulty:4,chief_complaint:'Mulher, 56 anos, teve dois episódios de dor torácica em repouso; está sem dor durante o ECG.',anamnesis:'Tabagismo prévio; sem infarto conhecido.',medications:'Nenhuma medicação cardiovascular regular.',vitals:'PA 128/78 mmHg • FC 72 bpm • FR 16 irpm • SpO₂ 98%',physical_exam:['Confortável no momento.','Exame cardiopulmonar sem alterações relevantes.'],labs:['Troponina normal ou apenas discretamente elevada.','K⁺ 4,2 mmol/L.'],imaging:'Ecocardiograma pode ser normal fora do episódio doloroso.',question:'Qual é a importância de ondas T profundas e simétricas em V2–V4 quando a paciente está sem dor?',answer:'Padrão de Wellens tipo B, sugestivo de doença crítica na artéria descendente anterior.',reasoning:'Ondas T profundamente invertidas e simétricas nas precordiais anteriores, em fase sem dor e com pouca alteração do ST, são características do padrão de Wellens no contexto clínico apropriado.',trap:'Tranquilizar-se porque a dor cessou e a troponina pode ser pouco alterada.',learning_point:'Wellens é um padrão de alto risco frequentemente visto no intervalo sem dor; reconhecer a morfologia é mais importante do que esperar supra de ST.'},
    {id:'isch_stt_10',p:'isch10',title:'Episódios recorrentes de dor com ECG quase normal',difficulty:4,chief_complaint:'Homem, 48 anos, com três episódios curtos de dor torácica em repouso nas últimas 24 horas; agora assintomático.',anamnesis:'Dislipidemia e forte história familiar de DAC.',medications:'Atorvastatina.',vitals:'PA 134/82 mmHg • FC 68 bpm • FR 16 irpm • SpO₂ 99%',physical_exam:['Sem sinais de congestão ou baixo débito.','Ausculta cardíaca sem sopros.'],labs:['Troponina discretamente acima do percentil 99.','Eletrólitos normais.'],imaging:'Ecocardiograma sem alteração segmentar evidente no momento.',question:'Como interpretar ondas T bifásicas predominantes em V2–V3 nesse contexto?',answer:'Padrão de Wellens tipo A.',reasoning:'Ondas T bifásicas em V2–V3, especialmente durante período sem dor após episódios anginosos, correspondem a uma forma clássica do padrão de Wellens.',trap:'Chamar a alteração de T de inespecífica por ser discreta e localizada.',learning_point:'Wellens pode se apresentar com T bifásica, sem grande elevação do ST e com biomarcadores pouco alterados.'},
    {id:'isch_stt_11',p:'isch11',title:'Dor intensa com depressão ascendente do ST',difficulty:5,chief_complaint:'Homem, 62 anos, com dor torácica intensa e contínua há 45 minutos, associada a sudorese.',anamnesis:'Hipertensão, diabetes e tabagismo ativo.',medications:'Metformina; losartana.',vitals:'PA 146/90 mmHg • FC 94 bpm • FR 21 irpm • SpO₂ 96%',physical_exam:['Diaforético e ansioso.','Sem estertores pulmonares.'],labs:['Troponina inicial pode ainda estar pouco elevada.','K⁺ 4,0 mmol/L.'],imaging:'Ecocardiograma com hipocinesia anterior.',question:'Que padrão de oclusão deve ser lembrado quando V2–V6 têm depressão ascendente do ST e T altas e simétricas?',answer:'Padrão de de Winter, associado a oclusão coronariana anterior aguda.',reasoning:'Depressão do ST no ponto J com ascensão em direção a ondas T altas e simétricas nas precordiais, frequentemente com discreta elevação em aVR, constitui o padrão de de Winter.',trap:'Descartar oclusão coronariana porque não existe o supra clássico nas precordiais.',learning_point:'Alguns padrões de oclusão aguda não apresentam o supra clássico; morfologia e contexto devem ser reconhecidos.'},
    {id:'isch_stt_12',p:'isch12',title:'Dor iniciada há poucos minutos com ondas T volumosas',difficulty:5,chief_complaint:'Mulher, 50 anos, com dor torácica súbita iniciada há cerca de 20 minutos.',anamnesis:'Hipertensão; sem doença renal.',medications:'Anlodipino.',vitals:'PA 152/90 mmHg • FC 86 bpm • FR 19 irpm • SpO₂ 98%',physical_exam:['Diaforese discreta.','Exame pulmonar normal.'],labs:['K⁺ 4,1 mmol/L.','Troponina inicial ainda dentro ou próxima do limite de referência.'],imaging:'ECG seriado é especialmente útil para observar evolução do padrão.',question:'Como diferenciar estas ondas T anteriores de uma simples variação ou hipercalemia?',answer:'Ondas T hiperagudas anteriores, compatíveis com fase muito precoce de oclusão coronariana.',reasoning:'As ondas T são amplas, volumosas e desproporcionais ao QRS em V2–V4, com discreta elevação inicial do ST e alterações recíprocas inferiores. Potássio normal e distribuição territorial apoiam isquemia aguda precoce.',trap:'Confundir toda onda T alta com hipercalemia; na hipercalemia o padrão tende a ser mais difuso e a T mais estreita/apiculada.',learning_point:'Ondas T hiperagudas podem preceder o supra de ST franco; ECG seriado ajuda a documentar a evolução.'},
    {id:'isch_stt_13',p:'isch13',title:'Elevação do ST em adulto jovem assintomático',difficulty:2,chief_complaint:'Homem, 27 anos, atleta recreacional, realiza ECG em avaliação de rotina e nega dor torácica.',anamnesis:'Sem fatores de risco cardiovasculares conhecidos. ECG semelhante documentado há dois anos.',medications:'Nenhuma.',vitals:'PA 118/70 mmHg • FC 58 bpm • FR 14 irpm • SpO₂ 99%',physical_exam:['Bom estado geral.','Exame cardiopulmonar normal.'],labs:['Troponina negativa quando dosada por outro motivo.','Eletrólitos normais.'],imaging:'Ecocardiograma prévio normal.',question:'A elevação côncava do ST em precordiais representa necessariamente infarto?',answer:'Padrão de repolarização precoce.',reasoning:'Elevação côncava do ST em V2–V5, com entalhe no ponto J, ausência de reciprocidade, ausência de sintomas e estabilidade em ECGs prévios favorece repolarização precoce.',trap:'Aplicar a regra “qualquer supra = infarto” sem considerar morfologia, distribuição, sintomas e comparação prévia.',learning_point:'Repolarização precoce é diagnóstico de contexto; um novo quadro de dor torácica exige reavaliação mesmo em quem tem padrão prévio.'},
    {id:'isch_stt_14',p:'isch14',title:'Dor pleurítica que melhora ao sentar',difficulty:3,chief_complaint:'Mulher, 34 anos, com dor torácica pleurítica após quadro viral, pior em decúbito e melhor ao inclinar-se para frente.',anamnesis:'Infecção respiratória viral na semana anterior. Sem fatores de risco coronarianos importantes.',medications:'Nenhuma.',vitals:'PA 122/74 mmHg • FC 96 bpm • FR 18 irpm • SpO₂ 98% • T 37,8 °C',physical_exam:['Sem sinais de insuficiência cardíaca.','Atrito pericárdico pode ser transitório e não estar presente.'],labs:['PCR elevada.','Troponina normal ou discretamente elevada se houver componente miopericárdico.'],imaging:'Ecocardiograma sem derrame significativo.',question:'Que diagnóstico explica elevação difusa e côncava do ST com padrão recíproco em aVR/V1?',answer:'Pericardite aguda.',reasoning:'O supra é difuso, não segue um único território coronariano e associa-se à clínica pleurítica/posicional. Depressão de PR, quando presente, e alterações opostas em aVR reforçam o padrão.',trap:'Localizar um “território de infarto” em uma alteração de ST difusa e não territorial.',learning_point:'Pericardite costuma produzir alterações difusas; a distribuição é tão importante quanto a forma do segmento ST.'},
    {id:'isch_stt_15',p:'isch15',title:'Alterações laterais de ST-T em hipertenso crônico',difficulty:3,chief_complaint:'Homem, 65 anos, encaminhado por hipertensão de longa data; nega dor torácica atual.',anamnesis:'Hipertensão há 20 anos, controle irregular.',medications:'Losartana; hidroclorotiazida com adesão irregular.',vitals:'PA 176/98 mmHg • FC 74 bpm • FR 16 irpm • SpO₂ 98%',physical_exam:['Ictus discretamente deslocado.','Sem sinais de congestão.'],labs:['Troponina sem elevação dinâmica.','Creatinina 1,2 mg/dL.'],imaging:'Ecocardiograma com hipertrofia ventricular esquerda concêntrica.',question:'Como explicar o alto QRS associado a depressão descendente de ST e T negativa em I/aVL/V5–V6?',answer:'Hipertrofia ventricular esquerda com alterações secundárias de repolarização (“strain”).',reasoning:'Voltagens elevadas compatíveis com HVE e alterações de ST-T discordantes nas derivações laterais formam um padrão de strain, especialmente no contexto de hipertensão crônica e ecocardiograma compatível.',trap:'Chamar automaticamente a depressão lateral de ST de SCA sem integrar voltagem, morfologia, sintomas e evolução.',learning_point:'HVE pode causar importantes alterações secundárias de ST-T e mimetizar isquemia; comparação com ECG prévio é valiosa.'},
    {id:'isch_stt_16',p:'isch16',title:'QRS largo com alterações discordantes de ST-T',difficulty:4,chief_complaint:'Mulher, 76 anos, com dispneia crônica estável, sem dor torácica aguda.',anamnesis:'Cardiomiopatia e bloqueio de ramo esquerdo conhecido há três anos.',medications:'Carvedilol; sacubitril/valsartana; furosemida.',vitals:'PA 126/76 mmHg • FC 70 bpm • FR 18 irpm • SpO₂ 96%',physical_exam:['Sem sinais novos de baixo débito.','Crepitações ausentes.'],labs:['Troponina sem variação significativa em coletas seriadas.','K⁺ 4,3 mmol/L.'],imaging:'ECG prévio mostra morfologia semelhante.',question:'As alterações de ST-T discordantes neste QRS largo significam infarto por si só?',answer:'Bloqueio de ramo esquerdo com alterações secundárias de repolarização.',reasoning:'O QRS largo e a morfologia típica de BRE produzem alterações secundárias e geralmente discordantes de ST-T. Isquemia aguda não deve ser diagnosticada ou excluída apenas por essa discordância; sintomas, comparação prévia, biomarcadores e critérios específicos são necessários.',trap:'Interpretar alterações secundárias esperadas do BRE como supra/depressão isquêmica primária.',learning_point:'Primeiro reconheça o distúrbio de condução; depois avalie se há alterações de ST-T desproporcionais ou não explicadas por ele.'},
    {id:'isch_stt_17',p:'isch17',title:'Supra persistente em paciente com infarto antigo',difficulty:4,chief_complaint:'Homem, 69 anos, assintomático, realiza ECG de seguimento cardiológico.',anamnesis:'IAM anterior extenso há seis anos. Nega dor atual.',medications:'AAS; estatina; betabloqueador; IECA.',vitals:'PA 124/72 mmHg • FC 66 bpm • FR 15 irpm • SpO₂ 98%',physical_exam:['Clinicamente estável.','Sem sinais de congestão.'],labs:['Troponina sem elevação.','Eletrólitos normais.'],imaging:'Ecocardiograma mostra aneurisma apical crônico; ECG antigo é semelhante.',question:'Como interpretar ondas Q/QS com elevação persistente do ST em V1–V4 sem sintomas agudos?',answer:'Aneurisma ventricular esquerdo pós-IAM com elevação persistente do ST.',reasoning:'Ondas Q/QS antigas, supra persistente estável, ausência de sintomas e documentação de aneurisma apical favorecem sequela crônica em vez de nova oclusão aguda.',trap:'Ignorar a história e o ECG prévio e tratar qualquer supra persistente como necessariamente novo.',learning_point:'Comparação com traçados anteriores e contexto temporal é essencial ao avaliar supra de ST crônico.'},
    {id:'isch_stt_18',p:'isch18',title:'Dor torácica após forte estresse emocional',difficulty:4,chief_complaint:'Mulher, 63 anos, com dor torácica e dispneia poucas horas após evento emocional intenso.',anamnesis:'Sem doença coronariana conhecida. Pós-menopausa.',medications:'Anlodipino.',vitals:'PA 138/82 mmHg • FC 104 bpm • FR 22 irpm • SpO₂ 96%',physical_exam:['Ansiosa, mas hemodinamicamente estável.','Sem sinais focais ao exame cardiopulmonar.'],labs:['Troponina discretamente elevada.','BNP elevado de forma desproporcional ao aumento da troponina.'],imaging:'Ecocardiograma com padrão transitório de balonamento apical; anatomia coronariana sem obstrução responsável quando investigada.',question:'Que mimetizador de SCA pode produzir inversões amplas de T nas precordiais após estresse intenso?',answer:'Cardiomiopatia de Takotsubo com alterações de repolarização.',reasoning:'O contexto de estresse, a alteração ventricular transitória e as inversões difusas/profundas de T com prolongamento de repolarização são compatíveis com Takotsubo. A apresentação pode imitar uma síndrome coronariana aguda.',trap:'Assumir que um ECG sugestivo permite distinguir Takotsubo de SCA sem investigação apropriada.',learning_point:'Takotsubo é diagnóstico de integração clínica, imagem e anatomia coronariana; o ECG sozinho não exclui oclusão coronariana.'},
    {id:'isch_stt_19',p:'isch19',title:'Fraqueza e palpitações em uso de diurético',difficulty:3,chief_complaint:'Mulher, 45 anos, com fraqueza muscular, câimbras e palpitações há dois dias.',anamnesis:'Hipertensão; aumentou por conta própria a dose do diurético durante uma viagem.',medications:'Hidroclorotiazida em dose maior que a prescrita.',vitals:'PA 116/70 mmHg • FC 92 bpm • FR 16 irpm • SpO₂ 99%',physical_exam:['Mucosas discretamente secas.','Sem dor torácica ou sinais de congestão.'],labs:['K⁺ 2,8 mmol/L.','Mg²⁺ 1,6 mg/dL; troponina negativa.'],imaging:'Sem achados estruturais agudos.',question:'Que alteração metabólica explica ST deprimido, T achatada e ondas U proeminentes?',answer:'Hipocalemia com alterações de repolarização.',reasoning:'Hipocalemia pode causar redução da amplitude da T, depressão de ST e ondas U proeminentes, especialmente em precordiais. O contexto medicamentoso e o potássio baixo sustentam o diagnóstico.',trap:'Confundir a combinação ST deprimido/T alterada com isquemia sem observar as ondas U e os eletrólitos.',learning_point:'Distúrbios eletrolíticos são mimetizadores importantes de alterações de ST-T; sempre integre o ECG aos exames laboratoriais.'},
    {id:'isch_stt_20',p:'isch20',title:'Fraqueza em paciente com doença renal crônica',difficulty:3,chief_complaint:'Homem, 72 anos, com fraqueza progressiva e parestesias, sem dor torácica.',anamnesis:'Doença renal crônica avançada e diabetes.',medications:'Losartana; espironolactona; insulina.',vitals:'PA 138/80 mmHg • FC 58 bpm • FR 17 irpm • SpO₂ 98%',physical_exam:['Consciente, sem sinais de congestão aguda.','Força global discretamente reduzida.'],labs:['K⁺ 6,8 mmol/L.','Creatinina 4,1 mg/dL; troponina sem padrão dinâmico de lesão aguda.'],imaging:'Sem alteração estrutural aguda relevante.',question:'Ondas T altas e apiculadas em várias derivações representam ondas hiperagudas isquêmicas?',answer:'Hipercalemia com ondas T apiculadas difusas.',reasoning:'Ondas T estreitas, pontiagudas e distribuídas de forma ampla, associadas a potássio muito elevado e discreto alargamento do QRS, favorecem hipercalemia em vez de um padrão territorial de oclusão coronariana.',trap:'Chamar qualquer T alta de “hiperaguda”; a distribuição territorial, a base da onda e o contexto laboratorial ajudam a diferenciar.',learning_point:'T hiperaguda isquêmica tende a ser ampla e territorial; a T hipercalêmica costuma ser estreita, apiculada e mais difusa.'}
  ];

  const EN=[
    {title:'Chest pain with nausea and diaphoresis',chief_complaint:'58-year-old man with severe substernal pressure for 50 minutes, with nausea and diaphoresis.',anamnesis:'Hypertension, dyslipidemia, and smoking. Continuous pressure not related to position or breathing.',medications:'Losartan; inconsistent atorvastatin use.',vitals:'BP 148/92 mmHg • HR 78 bpm • RR 18/min • SpO₂ 97% on room air',physical_exam:['Pale and diaphoretic, alert and oriented.','Regular heart sounds; lungs clear.'],labs:['High-sensitivity troponin is initially above the reference limit.','K⁺ 4.2 mmol/L; no relevant creatinine abnormality.'],imaging:'Bedside echocardiography shows subtle inferior regional hypokinesis.',question:'Which ST-T pattern is present, and which territory does it suggest?',answer:'Inferior ST-elevation myocardial infarction pattern.',reasoning:'ST elevation is present in II, III, and aVF with reciprocal depression in I and aVL. Contiguous-lead distribution, reciprocal changes, and the clinical presentation support acute inferior coronary occlusion.',trap:'The pain may be mislabeled as gastrointestinal; interpret the ECG by territorial distribution rather than the symptom label.',learning_point:'ST elevation in contiguous leads with reciprocal change provides stronger anatomic coherence.'},
    {title:'Progressive precordial pain in a patient with diabetes',chief_complaint:'64-year-old woman with severe precordial pain for 90 minutes and weakness.',anamnesis:'Type 2 diabetes, hypertension, and family history of premature coronary disease.',medications:'Metformin; amlodipine; rosuvastatin.',vitals:'BP 136/84 mmHg • HR 92 bpm • RR 20/min • SpO₂ 96%',physical_exam:['Anxious with preserved peripheral perfusion.','No signs of pulmonary congestion.'],labs:['High-sensitivity troponin rises on repeat testing.','K⁺ 4.0 mmol/L.'],imaging:'Echocardiography shows anteroseptal hypokinesis.',question:'Where are the main ST changes, and which ECG syndrome should be recognized?',answer:'Anterior ST-elevation myocardial infarction pattern.',reasoning:'ST elevation predominates in V2–V4 with mild extension to V1/V5 and reciprocal inferior depression, localizing an acute anterior/anteroseptal injury pattern.',trap:'A very early tracing may not yet contain Q waves; absence of Q waves does not exclude acute occlusion.',learning_point:'V2–V4 are key anterior leads; compare them with inferior leads and serial tracings.'},
    {title:'Rest chest pain radiating to the arm',chief_complaint:'52-year-old man with resting pressure-like chest pain radiating to the left arm for 40 minutes.',anamnesis:'Active smoker with obesity and sedentary lifestyle. No prior ECG available.',medications:'No regular cardiovascular medications.',vitals:'BP 154/96 mmHg • HR 88 bpm • RR 19/min • SpO₂ 98%',physical_exam:['Mild diaphoresis.','No relevant cardiac or pulmonary examination findings.'],labs:['Initial troponin is mildly elevated.','Electrolytes are within the expected range.'],imaging:'Echocardiography shows anterior and lateral regional abnormalities.',question:'Which walls are involved by the ST distribution?',answer:'Anterolateral ST-elevation myocardial infarction pattern.',reasoning:'ST elevation in I, aVL, and V3–V6 with reciprocal inferior changes forms a coherent anterolateral pattern.',trap:'Looking only at V3–V4 may underestimate the lateral extension.',learning_point:'Group contiguous leads by territory and describe the full extent rather than reading each lead in isolation.'},
    {title:'Chest pressure with subtle ECG abnormalities',chief_complaint:'60-year-old woman with recurrent chest pressure and diaphoresis; pain is currently mild.',anamnesis:'Dyslipidemia and peripheral arterial disease.',medications:'Prior aspirin use; statin.',vitals:'BP 142/86 mmHg • HR 82 bpm • RR 17/min • SpO₂ 97%',physical_exam:['No signs of heart failure.','Peripheral pulses palpable.'],labs:['High-sensitivity troponin shows a rising pattern.','Hemoglobin 13.1 g/dL.'],imaging:'Echocardiography shows no major global abnormality and possible focal lateral hypokinesis.',question:'Which territorial pattern can be recognized even when only a few leads are abnormal?',answer:'High-lateral acute injury pattern.',reasoning:'ST elevation in I and aVL with reciprocal depression in III/aVF supports a high-lateral injury pattern in the appropriate clinical context.',trap:'The small number of leads with elevation may make the finding look nonspecific.',learning_point:'Focal I/aVL changes gain significance when inferior reciprocal change and compatible symptoms are present.'},
    {title:'Chest pain, hypotension, and jugular venous distention',chief_complaint:'67-year-old man with severe chest pain, dizziness, and nausea.',anamnesis:'Hypertension; no known heart failure.',medications:'Hydrochlorothiazide; losartan.',vitals:'BP 86/58 mmHg • HR 64 bpm • RR 20/min • SpO₂ 95%',physical_exam:['Jugular venous distention is present.','Lungs are clear; extremities are cool.'],labs:['High-sensitivity troponin is elevated.','K⁺ 4.3 mmol/L.'],imaging:'Focused echocardiography suggests right-ventricular dysfunction.',question:'Beyond the inferior territory, which extension should be suspected and what additional recording would help?',answer:'Inferior MI with suspected right-ventricular involvement; obtain right-sided leads, especially V4R.',reasoning:'Inferior ST elevation with reciprocal I/aVL depression plus ST elevation in V1, hypotension, JVD, and clear lungs raises concern for RV involvement.',trap:'Reading V1 in isolation as an anterior pattern and ignoring the inferior-clinical context.',learning_point:'With inferior MI, hypotension, and clear lungs, assess for RV involvement and add right-sided leads.'},
    {title:'Chest pain with anterior ST depression',chief_complaint:'59-year-old man with substernal pain and diaphoresis for 70 minutes.',anamnesis:'Smoking and diabetes. Pain persists at rest.',medications:'Metformin; simvastatin.',vitals:'BP 132/80 mmHg • HR 84 bpm • RR 18/min • SpO₂ 96%',physical_exam:['No pulmonary congestion.','Peripheral perfusion preserved.'],labs:['High-sensitivity troponin is rising.','K⁺ 4.4 mmol/L.'],imaging:'Posterior leads V7–V9, when obtained, can help confirm the suspected pattern.',question:'Does ST depression in V1–V3 represent only anterior subendocardial ischemia?',answer:'Reciprocal pattern suggestive of posterior myocardial infarction.',reasoning:'Horizontal ST depression in V1–V3 with relatively tall R waves and upright T waves can be the mirror image of posterior ST elevation.',trap:'Automatically labeling all anterior ST depression as anterior subendocardial ischemia.',learning_point:'ST depression in V1–V3 plus tall R and upright T waves should prompt consideration of posterior injury and V7–V9 leads.'},
    {title:'Dyspnea and chest pressure with minimal exertion',chief_complaint:'71-year-old woman with chest pressure and dyspnea on minimal exertion, worse over the last several hours.',anamnesis:'Known coronary artery disease and diabetes.',medications:'Aspirin; atorvastatin; carvedilol.',vitals:'BP 150/88 mmHg • HR 96 bpm • RR 22/min • SpO₂ 95%',physical_exam:['No pleuritic pain.','No crackles; regular rhythm.'],labs:['High-sensitivity troponin shows a dynamic rise.','Hemoglobin 12.4 g/dL; K⁺ 4.1 mmol/L.'],imaging:'Echocardiography shows preserved ejection fraction with subtle lateral abnormality.',question:'How should horizontal ST depression in the lateral leads be interpreted?',answer:'Lateral subendocardial ischemia in a non-ST-elevation acute coronary syndrome context.',reasoning:'ST depression in I, aVL, and V4–V6 with T-wave abnormalities and dynamic biomarkers supports subendocardial ischemia. The ECG must be integrated with the clinical course.',trap:'Calling every ST depression “nonspecific” without considering morphology, distribution, symptoms, and evolution.',learning_point:'Serial ST-T changes and troponin dynamics are central to non-ST-elevation ACS assessment.'},
    {title:'Persistent pain with diffuse ST abnormalities',chief_complaint:'73-year-old man with persistent pressure-like chest pain and dyspnea.',anamnesis:'Known multivessel coronary disease, hypertension, and diabetes.',medications:'Aspirin; high-intensity statin; beta-blocker.',vitals:'BP 104/68 mmHg • HR 102 bpm • RR 24/min • SpO₂ 94%',physical_exam:['Cool skin with mildly delayed capillary refill.','No obvious new murmur.'],labs:['High-sensitivity troponin is significantly elevated.','Lactate is mildly elevated.'],imaging:'Echocardiography shows mild global hypokinesis.',question:'What does diffuse ST depression with ST elevation in aVR suggest?',answer:'High-risk diffuse subendocardial ischemia pattern.',reasoning:'Widespread ST depression with aVR elevation suggests global subendocardial ischemia and may occur with extensive coronary disease, left-main disease, or severe supply-demand mismatch. It does not identify one specific anatomy by itself.',trap:'Declaring definite left-main occlusion from the ECG alone.',learning_point:'aVR elevation with diffuse depression is a high-risk pattern, not a one-to-one marker of a single coronary lesion.'},
    {title:'Pain resolved before the ECG',chief_complaint:'56-year-old woman with two episodes of resting chest pain; she is pain-free during the ECG.',anamnesis:'Former smoker; no known prior MI.',medications:'No regular cardiovascular medication.',vitals:'BP 128/78 mmHg • HR 72 bpm • RR 16/min • SpO₂ 98%',physical_exam:['Comfortable at present.','No relevant cardiopulmonary findings.'],labs:['Troponin may be normal or only mildly elevated.','K⁺ 4.2 mmol/L.'],imaging:'Echocardiography may be normal while pain-free.',question:'What is the significance of deep symmetric T-wave inversion in V2–V4 while the patient is pain-free?',answer:'Wellens pattern type B, associated with critical LAD disease.',reasoning:'Deep symmetric anterior T-wave inversion during a pain-free interval with little ST-segment change is characteristic of Wellens syndrome in the appropriate context.',trap:'Being reassured because the pain resolved and troponin may be only slightly abnormal.',learning_point:'Wellens is often seen when pain has resolved; morphology matters more than waiting for classic ST elevation.'},
    {title:'Recurrent pain with an almost normal ECG',chief_complaint:'48-year-old man with three brief episodes of resting chest pain over 24 hours; currently asymptomatic.',anamnesis:'Dyslipidemia and strong family history of coronary disease.',medications:'Atorvastatin.',vitals:'BP 134/82 mmHg • HR 68 bpm • RR 16/min • SpO₂ 99%',physical_exam:['No congestion or low-output signs.','No murmur.'],labs:['Troponin is only slightly above the 99th percentile.','Electrolytes are normal.'],imaging:'Echocardiography has no clear regional abnormality at present.',question:'How should biphasic T waves predominantly in V2–V3 be interpreted in this context?',answer:'Wellens pattern type A.',reasoning:'Biphasic T waves in V2–V3 during a pain-free period after anginal episodes are a classic Wellens morphology.',trap:'Calling a subtle localized T-wave change nonspecific.',learning_point:'Wellens may present with biphasic T waves, minimal ST change, and only small biomarker abnormalities.'},
    {title:'Severe pain with upsloping ST depression',chief_complaint:'62-year-old man with severe continuous chest pain for 45 minutes and diaphoresis.',anamnesis:'Hypertension, diabetes, and active smoking.',medications:'Metformin; losartan.',vitals:'BP 146/90 mmHg • HR 94 bpm • RR 21/min • SpO₂ 96%',physical_exam:['Diaphoretic and anxious.','No pulmonary crackles.'],labs:['Initial troponin may still be only mildly elevated.','K⁺ 4.0 mmol/L.'],imaging:'Echocardiography shows anterior hypokinesis.',question:'Which occlusion pattern should be recognized when V2–V6 show upsloping ST depression with tall symmetric T waves?',answer:'de Winter pattern associated with acute anterior coronary occlusion.',reasoning:'J-point ST depression that slopes upward into tall symmetric precordial T waves, often with mild aVR elevation, is the de Winter pattern.',trap:'Excluding acute coronary occlusion because classic precordial ST elevation is absent.',learning_point:'Acute coronary occlusion can present without classic ST elevation; recognize established occlusion patterns.'},
    {title:'Very early chest pain with bulky T waves',chief_complaint:'50-year-old woman with sudden chest pain beginning about 20 minutes ago.',anamnesis:'Hypertension; no renal disease.',medications:'Amlodipine.',vitals:'BP 152/90 mmHg • HR 86 bpm • RR 19/min • SpO₂ 98%',physical_exam:['Mild diaphoresis.','Normal lung examination.'],labs:['K⁺ 4.1 mmol/L.','Initial troponin is still normal or near the reference limit.'],imaging:'Serial ECGs are particularly useful to assess evolution.',question:'How can these anterior T waves be distinguished from a normal variant or hyperkalemia?',answer:'Anterior hyperacute T waves compatible with very early coronary occlusion.',reasoning:'T waves are broad, bulky, and disproportionate to the QRS in V2–V4 with subtle early ST elevation and inferior reciprocal change. Normal potassium and territorial distribution support acute ischemia.',trap:'Equating every tall T wave with hyperkalemia.',learning_point:'Hyperacute ischemic T waves may precede frank ST elevation; serial ECGs can document the transition.'},
    {title:'ST elevation in an asymptomatic young adult',chief_complaint:'27-year-old recreational athlete undergoing a routine ECG; no chest pain.',anamnesis:'No known cardiovascular risk factors. A similar ECG was documented two years ago.',medications:'None.',vitals:'BP 118/70 mmHg • HR 58 bpm • RR 14/min • SpO₂ 99%',physical_exam:['Well appearing.','Normal cardiopulmonary examination.'],labs:['Troponin was negative when previously checked for another reason.','Electrolytes normal.'],imaging:'Prior echocardiography was normal.',question:'Does concave precordial ST elevation necessarily indicate myocardial infarction?',answer:'Early repolarization pattern.',reasoning:'Concave ST elevation in V2–V5 with J-point notching, no reciprocal change, no symptoms, and stability on prior ECGs favors early repolarization.',trap:'Applying a “any ST elevation equals infarction” rule without considering morphology, distribution, symptoms, and prior ECGs.',learning_point:'Early repolarization is contextual; new chest pain still requires reassessment even when a prior benign pattern exists.'},
    {title:'Pleuritic pain relieved by sitting forward',chief_complaint:'34-year-old woman with pleuritic chest pain after a viral illness, worse supine and improved leaning forward.',anamnesis:'Viral respiratory infection one week earlier. No major coronary risk factors.',medications:'None.',vitals:'BP 122/74 mmHg • HR 96 bpm • RR 18/min • SpO₂ 98% • T 37.8 °C',physical_exam:['No signs of heart failure.','A pericardial rub may be transient and absent on examination.'],labs:['CRP elevated.','Troponin normal or mildly elevated if myopericardial involvement is present.'],imaging:'Echocardiography shows no significant effusion.',question:'Which diagnosis explains diffuse concave ST elevation with opposite changes in aVR/V1?',answer:'Acute pericarditis.',reasoning:'The ST elevation is diffuse rather than confined to one coronary territory and matches a pleuritic/positional syndrome. PR depression, when present, and opposite aVR changes further support the pattern.',trap:'Trying to assign a single infarct territory to a diffuse nonterritorial ST pattern.',learning_point:'Pericarditis usually produces diffuse abnormalities; distribution matters as much as ST shape.'},
    {title:'Lateral ST-T abnormalities in chronic hypertension',chief_complaint:'65-year-old man referred for long-standing hypertension; no current chest pain.',anamnesis:'Hypertension for 20 years with inconsistent control.',medications:'Losartan; hydrochlorothiazide with inconsistent adherence.',vitals:'BP 176/98 mmHg • HR 74 bpm • RR 16/min • SpO₂ 98%',physical_exam:['Mildly displaced apical impulse.','No congestion.'],labs:['No dynamic troponin elevation.','Creatinine 1.2 mg/dL.'],imaging:'Echocardiography shows concentric left-ventricular hypertrophy.',question:'How can high QRS voltage with downsloping ST depression and T inversion in I/aVL/V5–V6 be explained?',answer:'Left-ventricular hypertrophy with secondary repolarization (“strain”) pattern.',reasoning:'High voltage compatible with LVH plus discordant lateral ST-T abnormalities creates a strain pattern, fitting chronic hypertension and echo-confirmed LVH.',trap:'Automatically labeling lateral ST depression as ACS without integrating voltage, morphology, symptoms, and evolution.',learning_point:'LVH can cause major secondary ST-T abnormalities and mimic ischemia; prior ECG comparison is valuable.'},
    {title:'Wide QRS with discordant ST-T changes',chief_complaint:'76-year-old woman with stable chronic dyspnea and no acute chest pain.',anamnesis:'Cardiomyopathy and known left bundle-branch block for three years.',medications:'Carvedilol; sacubitril/valsartan; furosemide.',vitals:'BP 126/76 mmHg • HR 70 bpm • RR 18/min • SpO₂ 96%',physical_exam:['No new low-output signs.','No crackles.'],labs:['No significant serial troponin change.','K⁺ 4.3 mmol/L.'],imaging:'Prior ECG shows a similar morphology.',question:'Do discordant ST-T changes in this wide QRS establish myocardial infarction by themselves?',answer:'Left bundle-branch block with secondary repolarization abnormalities.',reasoning:'LBBB produces a wide QRS and expected secondary, usually discordant ST-T changes. Acute ischemia cannot be diagnosed or excluded solely from that discordance; symptoms, prior ECG, biomarkers, and specific criteria are needed.',trap:'Interpreting expected secondary LBBB repolarization as primary ischemic ST elevation/depression.',learning_point:'Recognize the conduction abnormality first, then look for ST-T changes that are disproportionate or otherwise unexplained.'},
    {title:'Persistent ST elevation after a remote infarction',chief_complaint:'69-year-old man, asymptomatic, undergoing routine cardiology follow-up.',anamnesis:'Large anterior MI six years ago. No current chest pain.',medications:'Aspirin; statin; beta-blocker; ACE inhibitor.',vitals:'BP 124/72 mmHg • HR 66 bpm • RR 15/min • SpO₂ 98%',physical_exam:['Clinically stable.','No congestion.'],labs:['Troponin is not elevated.','Electrolytes normal.'],imaging:'Echocardiography shows a chronic apical aneurysm; an old ECG is similar.',question:'How should Q/QS waves with persistent ST elevation in V1–V4 be interpreted without acute symptoms?',answer:'Post-MI left-ventricular aneurysm with persistent ST elevation.',reasoning:'Old Q/QS waves, stable persistent ST elevation, absence of acute symptoms, and documented apical aneurysm favor a chronic sequela rather than a new acute occlusion.',trap:'Ignoring history and prior ECG and treating any persistent ST elevation as necessarily new.',learning_point:'Prior tracings and time course are essential when evaluating chronic ST elevation.'},
    {title:'Chest pain after intense emotional stress',chief_complaint:'63-year-old woman with chest pain and dyspnea a few hours after a major emotional event.',anamnesis:'No known coronary disease. Postmenopausal.',medications:'Amlodipine.',vitals:'BP 138/82 mmHg • HR 104 bpm • RR 22/min • SpO₂ 96%',physical_exam:['Anxious but hemodynamically stable.','No focal cardiopulmonary finding.'],labs:['Troponin is mildly elevated.','BNP is elevated out of proportion to the troponin rise.'],imaging:'Echocardiography shows transient apical ballooning; coronary anatomy has no culprit obstruction when evaluated.',question:'Which ACS mimic may produce broad precordial T-wave inversion after intense stress?',answer:'Takotsubo cardiomyopathy with repolarization abnormalities.',reasoning:'The stress trigger, transient ventricular pattern, and diffuse deep T-wave inversions with repolarization prolongation fit Takotsubo, which can closely mimic ACS.',trap:'Assuming the ECG alone can distinguish Takotsubo from ACS.',learning_point:'Takotsubo requires integration of clinical context, imaging, and coronary anatomy; ECG alone cannot exclude coronary occlusion.'},
    {title:'Weakness and palpitations while taking a diuretic',chief_complaint:'45-year-old woman with muscle weakness, cramps, and palpitations for two days.',anamnesis:'Hypertension; she independently increased her diuretic dose while traveling.',medications:'Hydrochlorothiazide above the prescribed dose.',vitals:'BP 116/70 mmHg • HR 92 bpm • RR 16/min • SpO₂ 99%',physical_exam:['Mildly dry mucous membranes.','No chest pain or congestion.'],labs:['K⁺ 2.8 mmol/L.','Mg²⁺ 1.6 mg/dL; troponin negative.'],imaging:'No acute structural finding.',question:'Which metabolic abnormality explains ST depression, flattened T waves, and prominent U waves?',answer:'Hypokalemia with repolarization abnormalities.',reasoning:'Hypokalemia can produce lower T-wave amplitude, ST depression, and prominent U waves, especially in precordial leads. The medication history and low potassium support the diagnosis.',trap:'Mistaking ST depression/T-wave change for ischemia without noticing U waves and electrolyte values.',learning_point:'Electrolyte disorders are important ST-T mimics; always integrate the ECG with laboratory data.'},
    {title:'Weakness in advanced chronic kidney disease',chief_complaint:'72-year-old man with progressive weakness and paresthesias, without chest pain.',anamnesis:'Advanced chronic kidney disease and diabetes.',medications:'Losartan; spironolactone; insulin.',vitals:'BP 138/80 mmHg • HR 58 bpm • RR 17/min • SpO₂ 98%',physical_exam:['Alert, without acute congestion.','Mild generalized weakness.'],labs:['K⁺ 6.8 mmol/L.','Creatinine 4.1 mg/dL; troponin has no dynamic acute-injury pattern.'],imaging:'No relevant acute structural abnormality.',question:'Do tall peaked T waves across many leads represent ischemic hyperacute T waves?',answer:'Hyperkalemia with diffuse peaked T waves.',reasoning:'Narrow, pointed T waves with broad distribution, marked hyperkalemia, and mild QRS widening favor hyperkalemia over a territorial coronary occlusion pattern.',trap:'Calling every tall T wave “hyperacute”; territory, wave base, and laboratory context help distinguish the causes.',learning_point:'Ischemic hyperacute T waves tend to be broad and territorial; hyperkalemic T waves are often narrow, peaked, and diffuse.'}
  ];

  function install(){
    const lesson=window.ECG_STUDY_CONTENT?.lessons?.ischemia;
    if(!lesson)return;
    const isEn=window.ECG_LANG==='en' || document.documentElement.lang==='en';
    lesson.cases=PT.map((pt,i)=>{
      const src=isEn?Object.assign({},pt,EN[i]||{}):Object.assign({},pt);
      delete src.p;
      return Object.assign(src,{ecg_image:ecgDataUri(pt.p),ecg_caption:isEn?'12-lead ECG • synthetic educational tracing':'ECG de 12 derivações • traçado educacional sintético'});
    });
  }

  install();
  window.ECG_ISCHEMIA_CASES={version:'2026.09',count:PT.length,regenerate:install};
})();