from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import Dict, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image

try:
    import cairosvg
except Exception:
    cairosvg = None

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "lessons"

LESSONS: Dict[str, dict] = {
    "fundamentals": {"title_pt":"Fundamentos do ECG","title_en":"ECG Fundamentals","ecg":"sinus","focus_pt":"Calibração, grade, ondas, intervalos e método sistemático.","focus_en":"Calibration, grid, waves, intervals, and a systematic reading method.","criteria_pt":["A 25 mm/s: 1 quadrado pequeno = 0,04 s; 1 grande = 0,20 s.","A 10 mm/mV: 10 mm no eixo vertical correspondem a 1 mV.","Sequência sugerida: frequência → regularidade → P → PR → QRS → ST-T → QT/QTc → conclusão."],"criteria_en":["At 25 mm/s: 1 small box = 0.04 s; 1 large box = 0.20 s.","At 10 mm/mV: 10 mm vertically corresponds to 1 mV.","Suggested sequence: rate → regularity → P → PR → QRS → ST-T → QT/QTc → conclusion."],"diff_pt":["Artefato versus arritmia verdadeira","Variação normal versus achado patológico","Erro de calibração versus alteração real"],"diff_en":["Artifact versus true arrhythmia","Normal variation versus pathologic finding","Calibration error versus true abnormality"],"pit_pt":["Dar um diagnóstico antes de checar calibração e qualidade.","Interpretar apenas a frequência e ignorar atividade atrial.","Usar um único achado isolado sem contexto do traçado completo."],"pit_en":["Naming a diagnosis before checking calibration and signal quality.","Interpreting rate alone while ignoring atrial activity.","Using a single isolated finding without the context of the full tracing."]},
    "normal": {"title_pt":"ECG normal e ritmo sinusal","title_en":"Normal ECG and Sinus Rhythm","ecg":"sinus","focus_pt":"Reconhecimento do ritmo sinusal e dos limites do termo “ECG normal”.","focus_en":"Recognition of sinus rhythm and the limits of the term “normal ECG”.","criteria_pt":["Onda P consistente antes de cada QRS.","Relação P:QRS 1:1 e PR relativamente estável.","Frequência de repouso adulta habitualmente entre 60 e 100 bpm, considerando o contexto."],"criteria_en":["Consistent P wave before each QRS.","1:1 P-to-QRS relationship with a relatively stable PR interval.","Adult resting rate is commonly 60–100 bpm, interpreted in context."],"diff_pt":["Ritmo juncional","Ritmo atrial ectópico","Taquicardia ou bradicardia sinusal"],"diff_en":["Junctional rhythm","Ectopic atrial rhythm","Sinus tachycardia or bradycardia"],"pit_pt":["Chamar todo ritmo regular de sinusal.","Ignorar P invertida ou ausente.","Confundir normalidade do ritmo com ausência de toda e qualquer alteração no ECG de 12 derivações."],"pit_en":["Calling every regular rhythm sinus rhythm.","Ignoring inverted or absent P waves.","Equating a normal rhythm with a completely normal 12-lead ECG."]},
    "sinus_brady": {"title_pt":"Bradicardia sinusal","title_en":"Sinus Bradycardia","ecg":"sinus_brady","focus_pt":"Ritmo sinusal com frequência reduzida, distinguindo adaptação fisiológica de doença.","focus_en":"Sinus rhythm at a reduced rate, distinguishing physiologic adaptation from disease.","criteria_pt":["Morfologia sinusal de P com relação P:QRS 1:1.","Frequência geralmente <60 bpm em adultos, sem usar o número isoladamente para definir gravidade.","PR e QRS podem permanecer normais."],"criteria_en":["Sinus P-wave morphology with a 1:1 P-to-QRS relationship.","Rate is generally <60 bpm in adults; the number alone does not define severity.","PR and QRS may remain normal."],"diff_pt":["Ritmo juncional","BAV avançado","Pausa sinusal / disfunção do nó sinusal"],"diff_en":["Junctional rhythm","Advanced AV block","Sinus pause / sinus node dysfunction"],"pit_pt":["Tratar atleta assintomático como se tivesse bradicardia patológica.","Ignorar medicações, hipotireoidismo, hipotermia e distúrbios eletrolíticos.","Usar frequência baixa sem confirmar P sinusal."],"pit_en":["Treating an asymptomatic athlete as if the bradycardia were pathologic.","Ignoring medications, hypothyroidism, hypothermia, and electrolyte disorders.","Using a low rate without confirming sinus P waves."]},
    "sinus_tachy": {"title_pt":"Taquicardia sinusal","title_en":"Sinus Tachycardia","ecg":"sinus_tachy","focus_pt":"Resposta sinusal acelerada e busca da causa subjacente.","focus_en":"Accelerated sinus response and identification of the underlying driver.","criteria_pt":["P sinusal antes de cada QRS, com relação 1:1.","Frequência >100 bpm em adulto em repouso, com início e término geralmente graduais.","QRS tipicamente estreito na ausência de bloqueio intraventricular."],"criteria_en":["Sinus P wave before each QRS with a 1:1 relationship.","Rate >100 bpm in a resting adult, usually with gradual onset and offset.","QRS is typically narrow unless intraventricular conduction disease is present."],"diff_pt":["TSV regular de QRS estreito","Flutter atrial com condução 2:1","Taquicardia atrial"],"diff_en":["Regular narrow-complex SVT","Atrial flutter with 2:1 conduction","Atrial tachycardia"],"pit_pt":["Chamar taquicardia sinusal de arritmia primária sem procurar causa.","Não procurar P escondida na onda T em frequências altas.","Confundir regularidade com TSV."],"pit_en":["Calling sinus tachycardia a primary arrhythmia without looking for an underlying cause.","Failing to look for P waves merging with T waves at high rates.","Equating regularity with SVT."]},
    "sinus_arrhythmia": {"title_pt":"Arritmia sinusal","title_en":"Sinus Arrhythmia","ecg":"sinus_arrhythmia","focus_pt":"Variação cíclica dos intervalos R-R com origem sinusal, frequentemente respiratória.","focus_en":"Cyclic variation in R-R intervals with sinus origin, often respiratory.","criteria_pt":["P sinusal precede cada QRS.","PR relativamente estável.","Variação gradual dos intervalos R-R, muitas vezes relacionada ao ciclo respiratório."],"criteria_en":["A sinus P wave precedes each QRS.","PR interval remains relatively stable.","R-R intervals vary gradually, often with respiration."],"diff_pt":["Fibrilação atrial","PACs frequentes","Pausas sinusais"],"diff_en":["Atrial fibrillation","Frequent PACs","Sinus pauses"],"pit_pt":["Confundir irregularidade fisiológica com fibrilação atrial.","Ignorar P sinusal claramente organizada.","Não diferenciar variação gradual de batimentos prematuros abruptos."],"pit_en":["Mistaking physiologic irregularity for atrial fibrillation.","Ignoring clearly organized sinus P waves.","Failing to distinguish gradual variation from abrupt premature beats."]},
    "afib": {"title_pt":"Fibrilação atrial","title_en":"Atrial Fibrillation","ecg":"afib","focus_pt":"Atividade atrial desorganizada com resposta ventricular irregular.","focus_en":"Disorganized atrial activity with an irregular ventricular response.","criteria_pt":["Intervalos R-R irregularmente irregulares.","Ausência de ondas P sinusais discretas e repetitivas.","Atividade de base pode ser fibrilatória, sem padrão atrial organizado."],"criteria_en":["Irregularly irregular R-R intervals.","No discrete, repetitive sinus P waves.","Baseline may show fibrillatory activity without organized atrial activation."],"diff_pt":["Flutter atrial com condução variável","PACs muito frequentes","Taquicardia atrial multifocal"],"diff_en":["Atrial flutter with variable conduction","Very frequent PACs","Multifocal atrial tachycardia"],"pit_pt":["Diagnosticar FA apenas porque o ritmo é irregular.","Confundir artefato com fibrilação da linha de base.","Ignorar QRS largo preexistente ou aberrância."],"pit_en":["Diagnosing AF solely because the rhythm is irregular.","Mistaking artifact for fibrillatory baseline activity.","Ignoring pre-existing wide QRS or aberrancy."],"guideline":"2023 ACC/AHA/ACCP/HRS Atrial Fibrillation Guideline"},
    "flutter": {"title_pt":"Flutter atrial","title_en":"Atrial Flutter","ecg":"flutter","focus_pt":"Atividade atrial macroreentrante organizada, frequentemente perto de 300/min.","focus_en":"Organized macro-reentrant atrial activity, often near 300/min.","criteria_pt":["Ondas F repetitivas, frequentemente em padrão serrilhado.","Condução AV pode ser 2:1, 3:1, 4:1 ou variável.","Resposta ventricular pode ser regular ou irregular conforme a condução."],"criteria_en":["Repetitive flutter waves, often sawtooth in appearance.","AV conduction may be 2:1, 3:1, 4:1, or variable.","The ventricular response may be regular or irregular depending on conduction."],"diff_pt":["Fibrilação atrial","Taquicardia atrial","TSV com frequência próxima de 150 bpm"],"diff_en":["Atrial fibrillation","Atrial tachycardia","SVT with a ventricular rate near 150 bpm"],"pit_pt":["Perder ondas F quando há condução 2:1.","Chamar toda taquicardia regular a 150 bpm de TSV sem procurar flutter.","Assumir que flutter sempre tem resposta ventricular regular."],"pit_en":["Missing flutter waves with 2:1 conduction.","Calling every regular tachycardia near 150 bpm SVT without looking for flutter.","Assuming atrial flutter always has a regular ventricular response."],"guideline":"2015 ACC/AHA/HRS Supraventricular Tachycardia Guideline"},
    "svt": {"title_pt":"Taquicardia supraventricular","title_en":"Supraventricular Tachycardia","ecg":"svt","focus_pt":"Taquicardia regular de QRS estreito com origem acima dos ventrículos.","focus_en":"Regular narrow-complex tachycardia arising above the ventricles.","criteria_pt":["Ritmo geralmente regular e rápido.","QRS tipicamente <120 ms na ausência de aberrância.","P pode estar invisível, retrógrada ou imediatamente antes/depois do QRS."],"criteria_en":["Rhythm is usually regular and fast.","QRS is typically <120 ms unless aberrancy is present.","P waves may be hidden, retrograde, or just before/after the QRS."],"diff_pt":["Taquicardia sinusal","Flutter 2:1","Taquicardia atrial"],"diff_en":["Sinus tachycardia","2:1 atrial flutter","Atrial tachycardia"],"pit_pt":["Ignorar início/término abruptos quando disponíveis.","Chamar todo QRS estreito rápido de AVNRT.","Não considerar aberrância ou pré-excitação quando o QRS é largo."],"pit_en":["Ignoring abrupt onset/termination when available.","Calling every fast narrow-complex rhythm AVNRT.","Failing to consider aberrancy or pre-excitation when QRS is wide."],"guideline":"2015 ACC/AHA/HRS Supraventricular Tachycardia Guideline"},
    "psvt": {"title_pt":"TSV paroxística","title_en":"Paroxysmal SVT","ecg":"psvt","focus_pt":"Episódios de taquicardia supraventricular com início e término abruptos.","focus_en":"Episodes of supraventricular tachycardia with abrupt onset and termination.","criteria_pt":["Taquicardia regular, frequentemente 150–250 bpm.","QRS geralmente estreito.","História de início/cessação súbitos ajuda a diferenciar de taquicardia sinusal."],"criteria_en":["Regular tachycardia, often 150–250 bpm.","QRS is usually narrow.","Abrupt onset/offset in the history helps distinguish it from sinus tachycardia."],"diff_pt":["AVNRT","AVRT","Taquicardia atrial focal"],"diff_en":["AVNRT","AVRT","Focal atrial tachycardia"],"pit_pt":["Determinar o mecanismo exato sem dados suficientes.","Desconsiderar pré-excitação no ECG basal.","Confundir taquicardia sinusal rápida com episódio paroxístico."],"pit_en":["Assigning an exact mechanism without enough data.","Overlooking pre-excitation on the baseline ECG.","Mistaking fast sinus tachycardia for a paroxysmal episode."],"guideline":"2015 ACC/AHA/HRS Supraventricular Tachycardia Guideline"},
    "pac": {"title_pt":"Extrassístole atrial (PAC)","title_en":"Premature Atrial Complex (PAC)","ecg":"pac","focus_pt":"Batimento atrial precoce com P ectópica e QRS geralmente estreito.","focus_en":"Early atrial beat with an ectopic P wave and usually narrow QRS.","criteria_pt":["P prematura com morfologia diferente da P sinusal.","QRS costuma ser estreito se a condução é normal.","Pausa subsequente tende a ser não totalmente compensatória."],"criteria_en":["Premature P wave with morphology different from the sinus P wave.","QRS is usually narrow with normal conduction.","The following pause is typically not fully compensatory."],"diff_pt":["PVC","Arritmia sinusal","Pausa sinusal"],"diff_en":["PVC","Sinus arrhythmia","Sinus pause"],"pit_pt":["Não procurar P prematura deformando a T anterior.","Chamar QRS aberrante após PAC de PVC automaticamente.","Ignorar padrão de pausa."],"pit_en":["Failing to look for a premature P wave deforming the preceding T wave.","Automatically calling an aberrantly conducted PAC a PVC.","Ignoring the pause pattern."]},
    "pvc": {"title_pt":"Extrassístole ventricular (PVC)","title_en":"Premature Ventricular Complex (PVC)","ecg":"pvc","focus_pt":"Despolarização ventricular prematura, tipicamente com QRS largo e morfologia bizarra.","focus_en":"Premature ventricular depolarization, typically with a wide, abnormal QRS morphology.","criteria_pt":["QRS prematuro e geralmente ≥120 ms.","Habitualmente sem P sinusal imediatamente precedente que conduza ao QRS.","Pode haver pausa compensatória completa."],"criteria_en":["Premature QRS, usually ≥120 ms.","Usually no immediately preceding sinus P wave conducting to the QRS.","A full compensatory pause may follow."],"diff_pt":["PAC com aberrância","Batimento de escape ventricular","Artefato"],"diff_en":["PAC with aberrancy","Ventricular escape beat","Artifact"],"pit_pt":["Usar QRS largo isoladamente para chamar PVC.","Ignorar prematuridade e relação com P.","Confundir artefato de movimento com ectopia ventricular."],"pit_en":["Using wide QRS alone to label a PVC.","Ignoring prematurity and the relationship to P waves.","Mistaking motion artifact for ventricular ectopy."]},
    "bigeminy": {"title_pt":"Bigeminismo ventricular","title_en":"Ventricular Bigeminy","ecg":"bigeminy","focus_pt":"Padrão alternado de batimento conduzido e PVC.","focus_en":"Alternating pattern of a conducted beat followed by a PVC.","criteria_pt":["Sequência repetitiva 1:1 entre batimento de base e PVC.","PVCs com acoplamento relativamente constante quando monomórficos.","O padrão pode gerar pulso periférico irregular."],"criteria_en":["Repeating 1:1 sequence of a baseline beat followed by a PVC.","PVCs may show relatively fixed coupling when monomorphic.","The pattern can produce an irregular peripheral pulse."],"diff_pt":["PACs em bigeminismo","Ectopia ventricular frequente sem padrão","Aberrância alternante"],"diff_en":["Atrial bigeminy","Frequent ventricular ectopy without a fixed pattern","Alternating aberrancy"],"pit_pt":["Confundir frequência de pulso com frequência elétrica.","Ignorar morfologia dos complexos prematuros.","Chamar qualquer alternância de bigeminismo ventricular sem provar origem ventricular."],"pit_en":["Confusing pulse rate with electrical rate.","Ignoring morphology of the premature complexes.","Calling any alternating pattern ventricular bigeminy without proving ventricular origin."]},
    "trigeminy": {"title_pt":"Trigeminismo ventricular","title_en":"Ventricular Trigeminy","ecg":"trigeminy","focus_pt":"Padrão repetitivo em que cada terceiro complexo é um PVC.","focus_en":"Repeating pattern in which every third complex is a PVC.","criteria_pt":["Dois batimentos conduzidos seguidos por um PVC, repetidamente.","PVC geralmente largo e prematuro.","O padrão é definido pela periodicidade, não pela quantidade total de PVCs."],"criteria_en":["Two conducted beats followed by one PVC, repeatedly.","PVC is typically wide and premature.","The pattern is defined by periodicity, not by the total number of PVCs."],"diff_pt":["Bigeminismo","Ectopia ventricular frequente não padronizada","PACs em trigeminismo"],"diff_en":["Bigeminy","Frequent non-patterned ventricular ectopy","Atrial trigeminy"],"pit_pt":["Contar PVCs sem reconhecer a sequência.","Confundir PAC aberrante com PVC.","Ignorar contexto de eletrólitos, isquemia e cardiopatia estrutural."],"pit_en":["Counting PVCs without recognizing the repeating sequence.","Mistaking an aberrant PAC for a PVC.","Ignoring the context of electrolytes, ischemia, and structural heart disease."]},
    "avb1": {"title_pt":"BAV de 1º grau","title_en":"First-Degree AV Block","ecg":"avb1","focus_pt":"Condução AV 1:1 com PR prolongado e constante.","focus_en":"1:1 AV conduction with a prolonged, constant PR interval.","criteria_pt":["Toda P conduz a um QRS.","PR >200 ms em adultos, de forma constante.","Não há batimentos bloqueados por definição."],"criteria_en":["Every P wave conducts to a QRS.","PR >200 ms in adults and remains constant.","There are no dropped beats by definition."],"diff_pt":["PR longo fisiológico ou medicamentoso","Mobitz I em fase inicial","Dissociação AV com coincidência aparente"],"diff_en":["Physiologic or drug-related PR prolongation","Early Mobitz I pattern","AV dissociation with apparent coincidental association"],"pit_pt":["Chamar BAV de 1º grau quando há P não conduzida.","Medir PR em apenas um ciclo ruim.","Ignorar drogas nodais e contexto clínico."],"pit_en":["Calling it first-degree AV block when a P wave is not conducted.","Measuring PR from a single poor-quality cycle.","Ignoring AV-nodal drugs and clinical context."],"guideline":"2018 ACC/AHA/HRS Bradycardia and Conduction Delay Guideline"},
    "mobitz1": {"title_pt":"BAV de 2º grau — Mobitz I","title_en":"Second-Degree AV Block — Mobitz I","ecg":"mobitz1","focus_pt":"Prolongamento progressivo do PR até uma P não conduzida (Wenckebach).","focus_en":"Progressive PR prolongation until a P wave is not conducted (Wenckebach).","criteria_pt":["PR aumenta progressivamente em uma sequência típica.","Ocorre uma P bloqueada sem QRS subsequente.","Após a pausa, o ciclo reinicia com PR mais curto."],"criteria_en":["PR progressively lengthens in a typical sequence.","A P wave is blocked and is not followed by QRS.","After the pause, the cycle restarts with a shorter PR."],"diff_pt":["PAC bloqueada","Mobitz II","Arritmia sinusal com P sobreposta à T"],"diff_en":["Blocked PAC","Mobitz II","Sinus arrhythmia with a P wave hidden in the T wave"],"pit_pt":["Não procurar P escondida na T.","Chamar qualquer batimento bloqueado de Mobitz II.","Ignorar o padrão progressivo do PR."],"pit_en":["Failing to look for a P wave hidden in the T wave.","Calling any dropped beat Mobitz II.","Ignoring the progressive PR pattern."],"guideline":"2018 ACC/AHA/HRS Bradycardia and Conduction Delay Guideline"},
    "mobitz2": {"title_pt":"BAV de 2º grau — Mobitz II","title_en":"Second-Degree AV Block — Mobitz II","ecg":"mobitz2","focus_pt":"Falha súbita de condução AV com PR constante nos batimentos conduzidos.","focus_en":"Sudden failure of AV conduction with a constant PR in conducted beats.","criteria_pt":["PR dos batimentos conduzidos permanece constante.","Uma P ocasional não é seguida de QRS.","QRS pode ser largo quando há doença infranodal associada."],"criteria_en":["PR interval of conducted beats remains constant.","An occasional P wave is not followed by QRS.","QRS may be wide when infranodal disease is present."],"diff_pt":["PAC bloqueada","Mobitz I atípico","BAV 2:1 em que o tipo não pode ser definido com segurança"],"diff_en":["Blocked PAC","Atypical Mobitz I","2:1 AV block where the type cannot be assigned confidently"],"pit_pt":["Rotular BAV 2:1 automaticamente como Mobitz II.","Não confirmar que a P é verdadeiramente sinusal e pontual.","Ignorar risco associado a doença de condução infranodal."],"pit_en":["Automatically labeling 2:1 AV block as Mobitz II.","Failing to confirm that the P wave is truly sinus and on time.","Ignoring the significance of infranodal conduction disease."],"guideline":"2018 ACC/AHA/HRS Bradycardia and Conduction Delay Guideline"},
    "avb3": {"title_pt":"BAV de 3º grau","title_en":"Third-Degree AV Block","ecg":"avb3","focus_pt":"Dissociação atrioventricular completa com ritmos atrial e ventricular independentes.","focus_en":"Complete atrioventricular dissociation with independent atrial and ventricular rhythms.","criteria_pt":["Ondas P e QRS seguem frequências independentes.","Não existe relação PR fixa.","A frequência ventricular é determinada pelo ritmo de escape."],"criteria_en":["P waves and QRS complexes follow independent rates.","There is no fixed PR relationship.","The ventricular rate is determined by the escape rhythm."],"diff_pt":["Dissociação AV isorrítmica","BAV avançado com condução ocasional","Artefato que obscurece P"],"diff_en":["Isorhythmic AV dissociation","Advanced AV block with occasional conduction","Artifact obscuring P waves"],"pit_pt":["Procurar um PR médio e perder a independência entre P e QRS.","Contar apenas QRS sem analisar frequência atrial.","Confundir coincidências ocasionais entre P e QRS com condução verdadeira."],"pit_en":["Looking for an average PR and missing the independence of P and QRS.","Counting only QRS complexes without analyzing the atrial rate.","Mistaking occasional P-QRS coincidences for true conduction."],"guideline":"2018 ACC/AHA/HRS Bradycardia and Conduction Delay Guideline"},
    "vt": {"title_pt":"Taquicardia ventricular","title_en":"Ventricular Tachycardia","ecg":"vt","focus_pt":"Taquicardia de QRS largo com origem ventricular; em dúvida, o raciocínio deve priorizar segurança.","focus_en":"Wide-complex tachycardia of ventricular origin; when uncertain, diagnostic reasoning should prioritize safety.","criteria_pt":["Ritmo rápido com QRS largo.","Pode haver dissociação AV, batimentos de captura ou fusão.","Morfologia monomórfica sugere ativação ventricular repetitiva por circuito ou foco estável."],"criteria_en":["Fast rhythm with wide QRS complexes.","AV dissociation, capture beats, or fusion beats may be present.","Monomorphic morphology suggests repetitive ventricular activation from a stable circuit or focus."],"diff_pt":["SVT com aberrância","Taquicardia antidrômica por via acessória","Ritmo estimulado rápido"],"diff_en":["SVT with aberrancy","Antidromic tachycardia using an accessory pathway","Rapid paced rhythm"],"pit_pt":["Assumir que paciente estável não pode ter TV.","Usar apenas um critério morfológico isolado.","Confundir artefato ou pacing com taquicardia ventricular."],"pit_en":["Assuming a stable patient cannot have VT.","Relying on a single morphology criterion.","Mistaking artifact or pacing for ventricular tachycardia."],"guideline":"2017 AHA/ACC/HRS Ventricular Arrhythmias Guideline"},
    "vf": {"title_pt":"Fibrilação ventricular","title_en":"Ventricular Fibrillation","ecg":"vf","focus_pt":"Atividade ventricular caótica sem complexos QRS organizados.","focus_en":"Chaotic ventricular activity without organized QRS complexes.","criteria_pt":["Traçado caótico, irregular, sem P, QRS ou T organizados.","Amplitude e frequência variam ao longo do registro.","No cenário clínico, deve ser distinguida de artefato com rapidez."],"criteria_en":["Chaotic, irregular tracing without organized P, QRS, or T waves.","Amplitude and frequency vary across the strip.","In clinical context, it must be rapidly distinguished from artifact."],"diff_pt":["Artefato intenso","Taquicardia ventricular polimórfica","Linha de base instável com ritmo organizado oculto"],"diff_en":["Severe artifact","Polymorphic ventricular tachycardia","Unstable baseline with an organized rhythm hidden underneath"],"pit_pt":["Interpretar o monitor sem verificar o paciente e outro sinal quando disponível.","Chamar TV polimórfica organizada de FV.","Confundir tremor ou artefato com atividade ventricular caótica."],"pit_en":["Interpreting the monitor without checking the patient and another signal when available.","Calling organized polymorphic VT ventricular fibrillation.","Mistaking tremor or artifact for chaotic ventricular activity."],"guideline":"2017 AHA/ACC/HRS Ventricular Arrhythmias Guideline"},
    "paced": {"title_pt":"Ritmo estimulado por marcapasso","title_en":"Paced Rhythm","ecg":"paced","focus_pt":"Reconhecimento de espículas, captura e padrão de estimulação ventricular.","focus_en":"Recognition of pacing spikes, capture, and ventricular pacing pattern.","criteria_pt":["Espícula de pacing pode preceder o QRS estimulado.","QRS ventricular estimulado costuma ser largo.","Captura significa despolarização apropriada após o estímulo."],"criteria_en":["A pacing spike may precede the paced QRS.","Ventricularly paced QRS is usually wide.","Capture means appropriate depolarization follows the pacing stimulus."],"diff_pt":["Artefato de monitor","BAV com ritmo de escape","QRS largo intrínseco sem pacing"],"diff_en":["Monitor artifact","AV block with escape rhythm","Intrinsic wide QRS without pacing"],"pit_pt":["Confundir toda linha vertical com espícula de marcapasso.","Não avaliar captura após cada estímulo visível.","Inferir funcionamento completo do dispositivo a partir de uma única derivação."],"pit_en":["Mistaking every vertical line for a pacing spike.","Failing to assess capture after each visible stimulus.","Inferring complete device function from a single lead."],"guideline":"2018 ACC/AHA/HRS Bradycardia and Conduction Delay Guideline"},
    "ischemia": {"title_pt":"Isquemia e alterações ST-T","title_en":"Ischemia and ST-T Changes","ecg":"sinus","focus_pt":"Leitura do segmento ST e onda T no contexto de um ECG de 12 derivações; uma única derivação não localiza isquemia.","focus_en":"ST-segment and T-wave interpretation in a 12-lead ECG context; a single lead cannot localize ischemia.","criteria_pt":["Avalie ST no ponto J e em derivações contíguas apropriadas.","Morfologia, distribuição territorial e alterações recíprocas importam.","A interpretação de isquemia exige ECG de 12 derivações e contexto clínico; não deve ser ensinada como diagnóstico por Lead II isolada."],"criteria_en":["Assess the ST segment at the J point and in appropriate contiguous leads.","Morphology, territorial distribution, and reciprocal changes matter.","Ischemia interpretation requires a 12-lead ECG and clinical context; it should not be taught as a diagnosis from isolated Lead II."],"diff_pt":["Repolarização precoce","Pericardite","Alterações secundárias a hipertrofia, bloqueio de ramo ou pacing"],"diff_en":["Early repolarization","Pericarditis","Secondary repolarization changes from hypertrophy, bundle branch block, or pacing"],"pit_pt":["Diagnosticar IAM por uma única derivação de treinamento.","Ignorar sintomas, troponina e ECG seriado.","Confundir alterações secundárias de repolarização com isquemia primária."],"pit_en":["Diagnosing MI from a single training lead.","Ignoring symptoms, troponin, and serial ECGs.","Mistaking secondary repolarization changes for primary ischemia."],"guideline":"2025 ACC/AHA/ACEP/NAEMSP/SCAI Acute Coronary Syndromes Guideline"}
}

ORDER = ["fundamentals","normal","sinus_brady","sinus_tachy","sinus_arrhythmia","afib","flutter","svt","psvt","paced","bigeminy","trigeminy","pvc","pac","avb1","mobitz1","mobitz2","avb3","vt","vf","ischemia"]

COMMON = {
    "pt": {"subtitle":"Guia aprofundado — ECG Lab","educational":"Material educacional. Os traçados são reconstruções sintéticas para treinamento e não representam pacientes reais. Não substitui avaliação clínica, protocolo institucional ou julgamento profissional.","p1":"1. Visão geral e objetivos","p2":"2. Fisiologia e mecanismo","p3":"3. Critérios no ECG","p4":"4. Diagnósticos diferenciais","p5":"5. Raciocínio clínico e armadilhas","p6":"6. Revisão ativa e referências","phys":"O ECG registra diferenças de potencial geradas pela despolarização e repolarização cardíacas. O nó sinusal inicia normalmente a ativação atrial; o nó AV introduz atraso fisiológico antes da condução pelo sistema His–Purkinje. A morfologia observada depende da origem do impulso, da sequência de ativação, da velocidade de condução e da orientação do vetor elétrico em relação à derivação.","method":"Use um método fixo: frequência → regularidade → atividade atrial → relação P/QRS → PR → largura e morfologia do QRS → ST-T → QT/QTc quando pertinente → conclusão. Em taquicardia, classifique primeiro como regular/irregular e QRS estreito/largo.","case":"Raciocínio recomendado","case_text":"1) Descreva o traçado sem nomear o diagnóstico. 2) Identifique os achados que realmente sustentam a hipótese. 3) Compare com pelo menos dois diferenciais. 4) Verifique se o contexto clínico muda a urgência ou a probabilidade. 5) Só então formule a conclusão.","questions":["Qual achado é indispensável para sustentar esse diagnóstico?","Qual é o principal diagnóstico diferencial e como você o separaria?","Que erro de interpretação seria mais provável neste padrão?","Quais dados adicionais seriam necessários antes de uma decisão clínica real?"],"refs":["Guyton & Hall. Textbook of Medical Physiology, 15th ed. — fisiologia cardiovascular e eletrofisiologia.","AHA/ACCF/HRS. Recommendations for the Standardization and Interpretation of the Electrocardiogram.","Diretriz específica do tema quando indicada abaixo."]},
    "en": {"subtitle":"In-depth guide — ECG Lab","educational":"Educational material. Tracings are synthetic reconstructions for training and do not represent real patients. This does not replace clinical assessment, institutional protocols, or professional judgment.","p1":"1. Overview and objectives","p2":"2. Physiology and mechanism","p3":"3. ECG criteria","p4":"4. Differential diagnosis","p5":"5. Clinical reasoning and pitfalls","p6":"6. Active review and references","phys":"The ECG records potential differences generated by cardiac depolarization and repolarization. The sinus node normally initiates atrial activation; the AV node provides physiologic delay before conduction through the His–Purkinje system. The observed morphology depends on impulse origin, activation sequence, conduction velocity, and the orientation of the electrical vector relative to the lead.","method":"Use a fixed sequence: rate → regularity → atrial activity → P/QRS relationship → PR → QRS width and morphology → ST-T → QT/QTc when relevant → conclusion. In tachycardia, first classify regular versus irregular and narrow versus wide QRS.","case":"Recommended reasoning","case_text":"1) Describe the tracing before naming a diagnosis. 2) Identify the findings that truly support the hypothesis. 3) Compare at least two differentials. 4) Decide whether clinical context changes urgency or probability. 5) Only then state the conclusion.","questions":["Which finding is essential to support this diagnosis?","What is the main differential and how would you separate it?","Which interpretation error is most likely with this pattern?","What additional data would be required before a real clinical decision?"],"refs":["Guyton & Hall. Textbook of Medical Physiology, 15th ed. — cardiovascular physiology and electrophysiology.","AHA/ACCF/HRS. Recommendations for the Standardization and Interpretation of the Electrocardiogram.","Topic-specific guideline when listed below."]}
}

def make_styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("Title2", parent=base["Title"], fontName="Helvetica-Bold", fontSize=22, leading=27, textColor=colors.HexColor("#07111f"), spaceAfter=8),
        "subtitle": ParagraphStyle("Subtitle", parent=base["Normal"], fontName="Helvetica", fontSize=10, leading=14, textColor=colors.HexColor("#5b6777"), spaceAfter=8),
        "h": ParagraphStyle("H", parent=base["Heading2"], fontName="Helvetica-Bold", fontSize=16, leading=20, textColor=colors.HexColor("#07111f"), spaceAfter=10),
        "body": ParagraphStyle("Body", parent=base["BodyText"], fontName="Helvetica", fontSize=10.2, leading=15, textColor=colors.HexColor("#1c2530"), spaceAfter=7),
        "bullet": ParagraphStyle("Bullet2", parent=base["BodyText"], fontName="Helvetica", fontSize=10.2, leading=15, leftIndent=12, firstLineIndent=-6, bulletIndent=4, spaceAfter=5),
        "note": ParagraphStyle("Note", parent=base["BodyText"], fontName="Helvetica", fontSize=8.8, leading=12.5, textColor=colors.HexColor("#54606e"), backColor=colors.HexColor("#f3f6f9"), borderPadding=8, spaceBefore=8, spaceAfter=8),
        "center": ParagraphStyle("Center", parent=base["BodyText"], alignment=TA_CENTER, fontSize=8.5, leading=11, textColor=colors.HexColor("#5b6777")),
    }

def header_footer(canvas, doc):
    canvas.saveState(); canvas.setStrokeColor(colors.HexColor("#d7dde5")); canvas.line(18*mm,15*mm,192*mm,15*mm); canvas.setFont("Helvetica",7.5); canvas.setFillColor(colors.HexColor("#657181")); canvas.drawString(18*mm,10*mm,"ECG Lab • Educational use only"); canvas.drawRightString(192*mm,10*mm,f"{doc.page}"); canvas.restoreState()

def bullets(items: List[str], st):
    return [Paragraph(f"• {x}", st["bullet"]) for x in items]

def ecg_image(category: str):
    path = ROOT / "assets" / "ecg" / category / f"{category}_01.svg"
    if not path.exists() or cairosvg is None: return None
    try:
        png = cairosvg.svg2png(bytestring=path.read_bytes(), output_width=1450)
        im = Image(BytesIO(png), width=174*mm, height=56*mm); im.hAlign="CENTER"; return im
    except Exception: return None

def build_pdf(key: str, lang: str):
    item=LESSONS[key]; c=COMMON[lang]; st=make_styles(); title=item[f"title_{lang}"]; focus=item[f"focus_{lang}"]; criteria=item[f"criteria_{lang}"]; diffs=item[f"diff_{lang}"]; pits=item[f"pit_{lang}"]
    out=OUT/lang/f"{key}.pdf"; out.parent.mkdir(parents=True, exist_ok=True)
    doc=SimpleDocTemplate(str(out), pagesize=A4, rightMargin=18*mm, leftMargin=18*mm, topMargin=18*mm, bottomMargin=20*mm, title=title, author="ECG Lab")
    story=[]; img=ecg_image(item["ecg"])
    story += [Paragraph(title,st["title"]),Paragraph(c["subtitle"],st["subtitle"]),Spacer(1,4),Paragraph(c["p1"],st["h"]),Paragraph(focus,st["body"])] + bullets(criteria[:2],st) + [Paragraph(c["educational"],st["note"])]
    if img: story += [Spacer(1,5),img,Paragraph(("Exemplo vetorial em Lead II para reconhecimento de ritmo." if lang=="pt" else "Vector Lead II example for rhythm recognition."),st["center"])]
    story.append(PageBreak())
    extra_pt={"afib":"Na fibrilação atrial, múltiplas frentes de ativação atrial impedem uma contração atrial organizada; a condução pelo nó AV varia batimento a batimento.","flutter":"No flutter típico, um circuito macroreentrante atrial produz atividade atrial rápida e organizada, e o nó AV determina a razão de condução aos ventrículos.","vt":"Na taquicardia ventricular, a ativação começa no miocárdio ventricular ou em circuito reentrante e se propaga fora da rede His–Purkinje normal, alargando o QRS.","vf":"Na fibrilação ventricular, a ativação elétrica ventricular é fragmentada e caótica, sem sequência mecânica eficaz correspondente.","avb3":"No BAV completo, os impulsos atriais não atravessam o sistema AV; um foco de escape distal mantém atividade ventricular independente."}
    extra_en={"afib":"In atrial fibrillation, multiple atrial wavefronts prevent organized atrial contraction; AV nodal conduction varies from beat to beat.","flutter":"In typical atrial flutter, a macro-reentrant atrial circuit produces rapid organized atrial activity, while the AV node determines the ventricular conduction ratio.","vt":"In ventricular tachycardia, activation begins in ventricular myocardium or a re-entrant circuit and spreads outside the normal His–Purkinje network, widening the QRS.","vf":"In ventricular fibrillation, ventricular electrical activation is fragmented and chaotic, without an effective mechanical sequence.","avb3":"In complete heart block, atrial impulses do not conduct through the AV system; a distal escape focus maintains independent ventricular activity."}
    extra=(extra_pt if lang=="pt" else extra_en).get(key,"")
    story += [Paragraph(c["p2"],st["h"]),Paragraph(c["phys"],st["body"]),Paragraph(focus,st["body"])]
    if extra: story.append(Paragraph(extra,st["body"]))
    story += [Paragraph(("Aplicação ao método" if lang=="pt" else "Application to the method"),st["h"]),Paragraph(c["method"],st["body"]),PageBreak()]
    story += [Paragraph(c["p3"],st["h"])] + bullets(criteria,st) + [Paragraph(("Checklist de leitura" if lang=="pt" else "Reading checklist"),st["h"])]
    checklist=(["Meça ou estime a frequência.","Determine se o ritmo é regular.","Procure atividade atrial e sua relação com QRS.","Analise PR e largura/morfologia do QRS.","Verifique ST-T apenas dentro das limitações da derivação disponível."] if lang=="pt" else ["Measure or estimate the rate.","Decide whether the rhythm is regular.","Look for atrial activity and its relationship to QRS.","Assess PR and QRS width/morphology.","Assess ST-T only within the limitations of the available lead."])
    story += bullets(checklist,st)
    if img: story += [Spacer(1,6),img]
    story.append(PageBreak())
    story += [Paragraph(c["p4"],st["h"])]
    data=[[('Diferencial' if lang=='pt' else 'Differential'),('Ponto de separação' if lang=='pt' else 'How to separate')]]
    for d in diffs: data.append([d,('Compare regularidade, P/atividade atrial, PR, largura do QRS e relação temporal.' if lang=='pt' else 'Compare regularity, P/atrial activity, PR, QRS width, and timing relationships.')])
    t=Table(data,colWidths=[63*mm,105*mm],repeatRows=1); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#eaf0f5')),('TEXTCOLOR',(0,0),(-1,0),colors.HexColor('#07111f')),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTNAME',(0,1),(-1,-1),'Helvetica'),('FONTSIZE',(0,0),(-1,-1),9),('LEADING',(0,0),(-1,-1),12),('GRID',(0,0),(-1,-1),0.4,colors.HexColor('#c8d0da')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),6),('RIGHTPADDING',(0,0),(-1,-1),6),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]))
    story += [t,Spacer(1,8),Paragraph(('Evite definir o diagnóstico apenas por um número; padrões temporais e relações entre ondas são mais informativos.' if lang=='pt' else 'Avoid defining the diagnosis from a single number; timing patterns and relationships among waves are more informative.'),st["note"]),PageBreak()]
    story += [Paragraph(c["p5"],st["h"]),Paragraph(c["case"],st["h"]),Paragraph(c["case_text"],st["body"]),Paragraph(('Armadilhas prioritárias' if lang=='pt' else 'Priority pitfalls'),st["h"])] + bullets(pits,st)
    story += [Paragraph(('Limite do módulo de uma derivação' if lang=='pt' else 'Single-lead module limitation'),st["h"]),Paragraph(('Este módulo usa predominantemente Lead II para treinamento de ritmo. Bloqueios de ramo, eixo, localização de isquemia e vários diagnósticos morfológicos exigem ECG de 12 derivações e não devem ser inferidos com confiança a partir de uma única derivação.' if lang=='pt' else 'This module predominantly uses Lead II for rhythm training. Bundle branch blocks, axis, ischemia localization, and many morphology-based diagnoses require a 12-lead ECG and should not be inferred confidently from a single lead.'),st["note"]),PageBreak()]
    story += [Paragraph(c["p6"],st["h"]),Paragraph(('Perguntas de autoavaliação' if lang=='pt' else 'Self-review questions'),st["h"])] + [Paragraph(f"{i+1}. {q}",st["body"]) for i,q in enumerate(c["questions"])] + [Paragraph(('Referências essenciais' if lang=='pt' else 'Core references'),st["h"])] + bullets(c["refs"],st)
    if item.get('guideline'): story.append(Paragraph(f"• {item['guideline']}",st["bullet"]))
    story += [Spacer(1,8),Paragraph(('Revisão editorial: setembro de 2026.' if lang=='pt' else 'Editorial review: September 2026.'),st["note"])]
    doc.build(story,onFirstPage=header_footer,onLaterPages=header_footer)

def main():
    missing=[k for k in ORDER if k not in LESSONS]
    if missing: raise SystemExit(f"Missing lesson definitions: {missing}")
    for lang in ('pt','en'):
        for key in ORDER: build_pdf(key,lang)
    pt=list((OUT/'pt').glob('*.pdf')); en=list((OUT/'en').glob('*.pdf'))
    if len(pt)!=21 or len(en)!=21: raise SystemExit(f"Expected 21 PDFs per language, got pt={len(pt)} en={len(en)}")
    print(f"Generated {len(pt)+len(en)} lesson PDFs in {OUT}")

if __name__ == '__main__': main()
